### ISSUE TITLE
Suggestion : Addition of 'Azure Fencing' for clusters as an alternative to SBD based fencing

### ISSUE THREAD

**Issue by shekharssorot2002** [Azure/sap-hana#1038]
Azure fencing agent is now available for SUSE as well as RHEL. This is easier to setup than SBD as it involves creating an RBAC role, an AD SP with role access on the Azure VM's and adding a resource type to the pacemaker cluster. Reduces cost as iSCSI VM's need not be created and failover is equally fast.

What to do : Terraform will create a role as per link :https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-rhel-pacemaker#1-create-a-custom-role-for-the-fence-agent      and create a service principal, grant the SP role access on the VM/s. The Fencing agent resource type can be added to the cluster via an Ansible/salt playbook or be done manually at a later stage.

**Comment by rukawata** [comment]
Hi @shekharssorot2002,
We do support azure fence agent for SLES (check [here](https://github.com/Azure/sap-hana/blob/f6e6b7fe322c3ad195cb5bfe5f689bbac6642ca6/deploy/ansible/roles/hana-os-clustering/tasks/cluster-Suse.yml#L147-L157)) and RHEL (check [here](https://github.com/Azure/sap-hana/blob/f6e6b7fe322c3ad195cb5bfe5f689bbac6642ca6/deploy/ansible/roles/hana-os-clustering/tasks/cluster-RedHat.yml#L59-L68)).

Thanks,
Nancy
