### ISSUE TITLE
Beta Branch: Incorrectly using string ARM_SUBSCRIPTION_ID rather than value of that variable

### ISSUE THREAD

**Issue by rtamalin** [Azure/sap-hana#1100]
https://github.com/Azure/sap-hana/blob/7d88ba083a0963f2e0ec97325db99902c2ff6f7e/deploy/scripts/installer.sh#L154

In my testing of the beta branch I was seeing errors during prepare_region.sh dur trying to lookup the subscription with an invalid subscription value; after a little investigation I found the above line. Changing it to read

     STATE_SUBSCRIPTION=${ARM_SUBSCRIPTION_ID}

gets past the problem.

**Comment by KimForss** [comment]
Fixed, sorry about this - still learning bash ;)

**Comment by rtamalin** [comment]
> Fixed, sorry about this - still learning bash ;)

Happy to help out with that once we get the collaboration stuff fully online.
