### ISSUE TITLE
[BUG] When using the prepare_region.sh on the beta branch, migration of the sap_library state fails because tfstate_resource_id is not defined

### ISSUE THREAD

**Issue by rtamalin** [Azure/sap-hana#1102]
**Describe the bug**
Using the Bash workflow from my Linux workstation, and a prepared workspace based upon the documentation WesternEurope region example (switching to WestUS region) I'm seeing the following error as part of the `terraform plan` step when migrating the library state:

```
#########################################################################################
#                                                                                       #
#                             Running Terraform plan                                    #
#                                                                                       #
#########################################################################################


Error: Invalid index

  on ../../../../sap-hana/deploy/terraform/run/sap_library/variables_local.tf line 22, in locals:
  22:   saplib_subscription_id       = split("/", local.tfstate_resource_id)[2]
    |----------------
    | local.tfstate_resource_id is ""

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../../../sap-hana/deploy/terraform/run/sap_library/variables_local.tf line 23, in locals:
  23:   saplib_resource_group_name   = split("/", local.tfstate_resource_id)[4]
    |----------------
    | local.tfstate_resource_id is ""

The given key does not identify an element in this collection value.


Error: Invalid index

  on ../../../../sap-hana/deploy/terraform/run/sap_library/variables_local.tf line 24, in locals:
  24:   tfstate_storage_account_name = split("/", local.tfstate_resource_id)[8]
    |----------------
    | local.tfstate_resource_id is ""

The given key does not identify an element in this collection value.
```

Digging into the scripting it appears that the `tfstate_parameter` value is empty for the `Migrating the library state` phase when executing this line of the `deploy/scripts/installer.sh`:

    terraform plan -var-file=$parameterfile $tfstate_parameter $landscape_tfstate_key_parameter $deployer_tfstate_key_parameter $terraform_module_directory > plan_output.log

From what I can determine it would appear that the tfstate_resource_id mustn't have been saved to the `${system_config_information}` file after the `Bootstrapping the library` phase...

**To reproduce**
1. Prepare  workspace based upon the example workspace.
2. Run the beta branch version of the `prepare_region.sh`, with the fix for #1100 included, as per the documentation.
3. Answer `Y` or `yes` as appropriate for the relevant prompts, and provide the SPN details when requested
4. See error (eventually)

**Expected behavior**
`prepare_regions.sh` should complete successfully.

**Additional context**

**Comment by KimForss** [comment]
Should be fixed now - please try

**Comment by rtamalin** [comment]
Verified as fixed.
