### ISSUE TITLE
Invalid value for variable authentication"

### ISSUE THREAD

**Issue by cjpark-sapcsa** [Azure/sap-hana#1134]
HI Team, 

Just checking does anyone see the error of line 31 and 45 ? 

chan@Azure:~/Azure_SAP_Automated_Deployment/WORKSPACES/SAP_LANDSCAPE/NP-EUS2-SAP00-INFRASTRUCTURE$ terraform plan  --var-file=NP-EUS2-SAP00-INFRASTRUCTURE.json                     \
>                 ../../../sap-hana/deploy/terraform/run/sap_landscape/
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Warning: "soft_delete_enabled": [DEPRECATED] Azure has removed support for disabling Soft Delete as of 2020-12-15, as such this field is no longer configurable and can be safely removed. This field will be removed in version 3.0 of the Azure Provider.

  on ../../../sap-hana/deploy/terraform/terraform-units/modules/sap_landscape/key_vault_sap_landscape.tf line 7, in resource "azurerm_key_vault" "kv_prvt":
   7: resource "azurerm_key_vault" "kv_prvt" {

(and one more similar warning elsewhere)

Error: Invalid value for variable

  on ../../../sap-hana/deploy/terraform/run/sap_landscape/variables_global.tf line 31:
  31: variable "authentication" {

Either ssh keys or user credentials must be specified.

This was checked by the validation rule at
../../../sap-hana/deploy/terraform/run/sap_landscape/variables_global.tf:37,3-13.

Error: Unsupported attribute

  on ../../../sap-hana/deploy/terraform/run/sap_landscape/variables_global.tf line 45, in variable "authentication":
  45:       length(trimspace(var.authentication.username)) != 0
    |----------------
    | var.authentication is object with no attributes

This object does not have an attribute named "username".

variable "authentication" {
  description = "Details of ssh key pair"
  default = {
    username = "azureadm"
  }

  validation {
    condition = (
      length(var.authentication) >= 1
    )
    error_message = "Either ssh keys or user credentials must be specified."
  }
  validation {
    condition = (
      length(trimspace(var.authentication.username)) != 0
    )
    error_message = "The default username for the Virtual machines must be specified."
  }
}

**Comment by KimForss** [comment]
Which branch are you using?

Check [DEV-NOEU-SAP02-INFRASTRUCTURE.json] (https://github.com/Azure/sap-hana/blob/beta/documentation/SAP_Automation_on_Azure/Process_Documentation/WORKSPACES/LANDSCAPE/DEV-NOEU-SAP02-INFRASTRUCTURE/DEV-NOEU-SAP02-INFRASTRUCTURE.json) for how to specify the variable

The block exists so that customers may specify the root automation account name

I also just uploaded 5 sample deployments here: https://github.com/Azure/sap-
hana/blob/beta/documentation/SAP_Automation_on_Azure/Process_Documentation/sample_deployments.md

**Comment by cjpark-sapcsa** [comment]
Thanks Kim Forss,

I followed Documentation/v2.3.0-d0 Initial Revision #1046 which bit old version. After add 

  "authentication": {
        "username"                      : "azureadm"
    },

I can finished the deployment.  thanks
