### ISSUE TITLE
[BUG] Graphic not displayed (bad link)

### ISSUE THREAD

**Issue by brmccutc** [Azure/sap-hana#1173]
On https://github.com/Azure/sap-hana/blob/master/documentation/SAP_Automation_on_Azure/Software_Documentation/product_documentation-deployer.md the graphic (.png) file (./../images/deployer.png) is not displayed.

**To reproduce**
1. Go to https://github.com/Azure/sap-hana/blob/master/documentation/SAP_Automation_on_Azure/Software_Documentation/product_documentation-deployer.md
2. Scroll down to the 'Deployment infrastructure' section.
3. See issue (and when clicking on /../images/deployer.png, a 404 error is displayed.

**Expected behavior**
The intended SAP Deployment Automation Framework - Deployer graphic is displayed.

**Comment by KimForss** [comment]
Resolved, the problem was in the image file name - it is case sensitive
