### ISSUE TITLE
Connection to Deployer VM puplib IP times out, therefore Prepare Region step sometimes fails

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#1299]
**Describe the bug**
Connection to Deployer VM times out, therefore Prepare Region step sometimes fails
Setting larger ssh_timout parameter doesn't help.

**To reproduce**
1. run the prepare region script
2. sometimes timeouts prevent connections to the deployer
4. configure_deployer.tf 

**Expected behavior**
No timeout errors. 

**Additional context**
Maybe a loop with 3 tries and some wait time of 30 seconds can be added

**Comment by KimForss** [comment]
Fixed in alfa
