### ISSUE TITLE
sap-hana/deploy/scripts/install_library.sh: line 149: [: false: unary operator expected[BUG]

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#1300]
**Describe the bug**
line 149 in install_library.sh : if [ false != $use_deployer ] must be if [ false != "$use_deployer" ]
adding "

**To reproduce**
deploy the prepare region from devops shows this error

**Expected behavior**
no error

**Additional context**
please add the quotes in the if clause

**Comment by KimForss** [comment]
Resolved in alfa branch
