### ISSUE TITLE
System Database User (SYSTEM) Password is invalid

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#1307]
**Describe the bug**
System Database User (SYSTEM) Password is invalid\n    
System Database User (SYSTEM) Password must contain at least one digit"

**To reproduce**
Install HANA DB

**Expected behavior**
Password in key vault contains at least one digit

**Additional context**
none

**Comment by KimForss** [comment]
Resolved in alfa.

As the password is created by Ansible re-running Terraform will not resolve it, to fix it
- update/remove the secret (if existing deployment)
