### ISSUE TITLE
NSG Error when deploying

### ISSUE THREAD

**Issue by dariustehrani** [Azure/sap-hana#135]
Hi,
when trying to execute the single node hana deployment we are facing the following issue. Kindly asking for some advise. Thanks a lot.

`azurerm_network_security_group.sap_nsg: Error creating/updating NSG "HN1-nsg" (Resource Group "hanademo"): network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SecurityRuleParametersMissing" Message="Required security rule parameters are missing for security rule with Id: /subscriptions/REMOVEDSUBSCRIPTION/resourceGroups/hanademo/providers/Microsoft.Network/networkSecurityGroups/HN1-nsg/securityRules/open-hana-db-ports. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups." Details=[]`

Kind Regards,
Darius

**Comment by pabowers** [comment]
I believe that I pushed a change recently and forgot to update the documentation.  If you are trying to open all ports, you can simply omit the input variable `allow_ips`.  Please let me know if doing that resolves your problem.
