### ISSUE TITLE
Any plan to support Rehat distribution? Most US customers are using RedHat by default.

### ISSUE THREAD

**Issue by sjyang18** [Azure/sap-hana#138]

**Comment by abhinababasu** [comment]
Redhat is in our plans but we have not started working on this.  We will share more details as they become available. We have modeled our timelines based on requirements we have received and most of them are on SLES. We would love to have a conversation around the scenarios you are looking at. Please drop an email to sap-hana AT microsoft DOT com

**Comment by ben-moss** [comment]
RHEL support should be delivered very soon in https://github.com/Azure/sap-hana/milestone/3
@mkdeegan @rukawata I think this question can be closed now, right?

**Comment by rukawata** [comment]
We can close it once we have v2 completely with RHEL HA.

**Comment by ben-moss** [comment]
Closing as discussed above @rukawata  :)
