### ISSUE TITLE
Not compatible with Terraform v0.12

### ISSUE THREAD

**Issue by mschlarb** [Azure/sap-hana#158]
Please see https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html
Upgrading via "terraform 0.12upgrade" works module by module, but nonetheless this should be mentioned.

**Comment by tniek** [comment]
Thanks for opening this issue; we've reflected the dependency with Terraform 0.11 in our documentation and included steps to download the latest compatible version (0.11.14) for Cloud Shell deployments.

We're currently in the process of completely refactoring our scripts to take advantage of the enhancements in Terraform 0.12.

**Comment by tniek** [comment]
This issue has been resolved; the current version of our templates are compatible with TF 0.12.2 and higher. Thanks again for bringing this to our attention!
