### ISSUE TITLE
HANA Installation fails due to missing OS Libraries

### ISSUE THREAD

**Issue by angeleja** [Azure/sap-hana#218]
HANA Installation fails due to missing OS Libraries

Required OS libaries : libatomic1, libgcc_s1 and libstdc++6 needs to be installed in Hana servers as part of the code.
Need help on how to incorporate this to the code. Thanks.

"Scanning software locations...", "Detected components:", "    SAP HANA Database (2.00.042.00.1564994110) in /hana/shared/install/SAP_HANA_DATABASE/server", "Log file written to '/var/tmp/hdb_HA1_hdblcm_install_2019-09-03_09.50.09/hdblcm.log' on host 'ha1-hdb0'."]}
fatal: [ha1-hdb1]: FAILED! => {"changed": true, "cmd": "pwd=$(<../hdbserver_HA1_passwords.xml); rm ../hdbserver_HA1_passwords.xml; echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_HA1_install.cfg' --read_password_from_stdin=xml", "delta": "0:00:01.217988", "end": "2019-09-03 09:50:10.534197", "msg": "non-zero return code", "rc": 1, "start": "2019-09-03 09:50:09.316209", "stderr": "rpm package 'libatomic1' is not installed\nThe operating system is not ready to perform gcc 7 assemblies\nFor more information, see SAP Note 2593824.\nChecking system requirements failed", "stderr_lines": ["rpm package 'libatomic1' is not installed", "The operating system is not ready to perform gcc 7 assemblies", "For more information, see SAP Note 2593824.", "Checking system requirements failed"], "stdout": "\n\nSAP HANA Lifecycle Management - SAP HANA Database 2.00.042.00.1564994110\n************************************************************************\n\n\nScanning software locations...\nDetected components:\n    SAP HANA Database (2.00.042.00.1564994110) in /hana/shared/install/SAP_HANA_DATABASE/server\nLog file written to '/var/tmp/hdb_HA1_hdblcm_install_2019-09-03_09.50.09/hdblcm.log' on host 'ha1-hdb1'.", "stdout_lines": ["", "", "SAP HANA Lifecycle Management - SAP HANA Database 2.00.042.00.1564994110", "************************************************************************", "", "", "Scanning software locations...", "Detected components:", "    SAP HANA Database (2.00.042.00.1564994110) in /hana/shared/install/SAP_HANA_DATABASE/server", "Log file written to '/var/tmp/hdb_HA1_hdblcm_install_2019-09-03_09.50.09/hdblcm.log' on host 'ha1-hdb1'."]}

**Comment by rukawata** [comment]
Hi,

This is due to missing system software packages to run SAP applications compiled with GCC 7.x on RHEL or SLES (SAP Note 2593824).

On SLES please install it with zypper:
`# zypper install libgcc_s1 libstdc++6 libatomic1`

Thanks,
Nancy

**Comment by angeleja** [comment]
Thanks for your reply. 
I would like to ask help on how to incorporate in the code during the build of HANA Vms and installation of OS Libraries.
So that when we run terraform apply these libraries are automatically deployed as well.
# zypper install libgcc_s1 libstdc++6 libatomic1

**Comment by rukawata** [comment]
Hi,

This is because our current script only supports HANA 1.0 and HANA 2.0 below SP04 [(issue 184)](https://github.com/Azure/sap-hana/issues/184)
We are refactoring the code at the moment, but will add supportability to install HANA 2.0 SP04 as soon as we can.

Since this is tracked in  [issue 184](https://github.com/Azure/sap-hana/issues/184), this one will be closed.

Thanks,
Nancy
