### ISSUE TITLE
fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'hdb0'"}

### ISSUE THREAD

**Issue by netz007** [Azure/sap-hana#222]
Hi,

I getting error like that:

module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): TASK [stonith-device-creation : Configure STONITH timeout] *********************
module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): fatal: [localhost]: FAILED! => {"msg": "'dict object' has no attribute 'hdb0'"}
module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec):  to retry, use: --limit @/home/saponazure/sap-hana/deploy/vm/ansible/ha_pair_playbook.retry

module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): PLAY RECAP *********************************************************************
module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): localhost                  : ok=7    changed=0    unreachable=0    failed=1

Regards,
Sebastian

**Comment by rukawata** [comment]
Hi Sebastian,

Can you attach the full log when you do `terraform apply`?
Also it would be great if you could also provide us the `terraform.tfvars` to us if we need to reproduce the problem you encounter.

Thanks,
Nancy

**Comment by rukawata** [comment]
Close this issue since there is no response for over 5 months.
