### ISSUE TITLE
HA Cluster Join fails (using Azure Shell)

### ISSUE THREAD

**Issue by stephenmogg** [Azure/sap-hana#270]
Build fails with error when second node joins the cluster.
Tried in multiple regions, used fresh clone of the the project in Azure Shell.

TASK [ha-cluster-join : HA cluster join csync2] ********************************
changed: [ha1-hdb1]

TASK [ha-cluster-join : HA cluster join cluster] *******************************
fatal: [ha1-hdb1]: FAILED! => {"changed": true, "cmd": "ha-cluster-join -y cluster", "delta": "0:00:05.717640", "end": "2019-11-26 10:54:22.156122", "msg": "non-zero return code", "rc": 1, "start": "2019-11-26 10:54:16.438482", "stderr": "ERROR: cluster.join: No value for ring0", "stderr_lines": ["ERROR: cluster.join: No value for ring0"], "stdout": "  Probing for new partitions...done\n  No existing IP/hostname specified - skipping mountpoint detection/creation", "stdout_lines": ["  Probing for new partitions...done", "  No existing IP/hostname specified - skipping mountpoint detection/creation"]}

PLAY RECAP *********************************************************************
ha1-hdb0                   : ok=63   changed=33   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
ha1-hdb1                   : ok=60   changed=30   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
hanaonazuresm-iscsi        : ok=42   changed=19   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

**Comment by persiaAziz** [comment]
Hey Stephen, are you still seeing this issue?

**Comment by stephenmogg** [comment]
Just tried again today.  (re cloned the project) and get exactly the same issue.

**Comment by persiaAziz** [comment]
A fix has been submitted : https://github.com/Azure/sap-hana/pull/272/files .. Can you please try my branch and see if this helps? Thanks

**Comment by stephenmogg** [comment]
Hi - Sorry to take so long to test.  Just tried today and this works fine.  Thanks for the fix.

**Comment by stephenmogg** [comment]
Recent fix merged in has resolved issue and cluster builds perfectly.  Thanks.
