### ISSUE TITLE
additional ports to be opened for bastion VM

### ISSUE THREAD

**Issue by takhoshi** [Azure/sap-hana#273]
TCP 3389 and 5986 need to be opened in the NSG for bastion VM otherwise no one can remotely connect the bastion VM.  https://github.com/Azure/sap-hana/blob/master/deploy/vm/modules/common_setup/nsg.tf

**Comment by rukawata** [comment]
Hi Taka,

3389 and 5986 should be opened according to [here](https://github.com/Azure/sap-hana/blob/master/deploy/vm/modules/windows_bastion_host/main.tf):

```
resource "azurerm_network_security_group" "windows_bastion_nsg" {
...

  security_rule {
    name                       = "RDP"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = local.rdp_port
    source_address_prefixes    = var.allow_ips
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "winrm"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = local.winrm_port
    source_address_prefixes    = var.allow_ips
    destination_address_prefix = "*"
  }
...
}
```
**_rdp_port_** and **_winrm_port_** are local [variables](https://github.com/Azure/sap-hana/blob/master/deploy/vm/modules/windows_bastion_host/variables.tf)with value 3389 and 5986:

```
locals {
...
  winrm_port   = 5986
  rdp_port     = 3389
}
```

Please let us know if I missed anything.

Thanks,
Nancy

**Comment by takhoshi** [comment]
Hi Nancy, terraform apply fails in the middle of execution with the following message. The NIC public IP of the Windows Bastion VM is 13.84.52.138 and the VM is attached to 2 NSGs (HN1_nsg and windows_bastion_nsg). TCP 3389 and 5986 are allowed only with windows_bastion_nsg, that's associated to the public IP hn1_win-bastion-nic. 

Let me know if you need further clarification from me. 

>>>>>

PLAY [win_bastion] *************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [hn1-win-bastion]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPSConnectionPool(host='13.84.52.138', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f495c2750>, 'Connection to 13.84.52.138 timed out. (connect timeout=30)'))", "unreachable": true}

PLAY RECAP *********************************************************************
hn1-hdb0                   : ok=18   changed=13   unreachable=0    failed=0    skipped=32   rescued=0    ignored=0
hn1-win-bastion            : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
>>>>>>

**Comment by rukawata** [comment]
@takhoshi Can you provide the terraform.tfvar that you use? So I could take a closer look.

Thanks,
Nancy

**Comment by takhoshi** [comment]
Thanks Nancy, I've confirmed this issue was resolved and everything is working fine !
