### ISSUE TITLE
Bug: Addition of Prometheus changes break existing deployments

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#287]
### Summary

The latest changes made to the `master` repo in #286 seem to have broken deployments that were working prior to that PR's merge.

### Steps to Reproduce

1. Checkout and use v2 code prior to #286 (e.g. `git checkout 94fac2a53677ccf3e0f2680bf2e2311535e77a72`)
1. Do all the basic setup, like SP, Terraform Init, etc. (if not done already)
1. Ensure you have no local changes/config in files, other than SAP media download credentials set in example template
1. From the project root, run the deploy: `terraform apply -auto-approve -var-file=deploy/v2/template_samples/single_node_hana.json deploy/v2/terraform/`

### Expected Behaviour

Deployment completes successfully without error.

### Actual Behaviour

Deployment fails at the Ansible stage, on the following task:

```text
TASK [enable-prometheus : Set OS version] ****************************************************************************************
fatal: [10.1.2.4]: FAILED! => {"msg": "The conditional check 'output.options.enable_prometheus == True' failed. The error was: error while evaluating conditional (output.options.enable_prometheus == True): 'dict object' has no attribute 'options'\n\nThe error appears to be in '/home/azureadm/sap-hana/deploy/v2/ansible/roles/enable-prometheus/tasks/main.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set OS version\n  ^ here\n"}
```

### Relevant Resources (URLs, screenshots, logs, etc.)

The following is expecting `output.options` to exist, but it doesn't if the customer is using a codebase version prior to #286 (at the time of writing this is the very latest, so unlikely that the customer might have updated):

https://github.com/Azure/sap-hana/blob/4f1795550f25a535c5078a25ce02a3527d1e8fd5/deploy/v2/ansible/sap_playbook.yml#L38

### Possible fixes

1. A trivial fix might be to use something along these lines (⚠️code not tested ⚠️):
   ```
   when:
     - output.options is defined
     - (output.options.enable_prometheus is defined) and output.options.enable_prometheus
   ```
1. A more robust best practice for avoiding similar issues would be to provide defaults for all role variables (i.e. don't expect the calling code to be smart enough to have defined everything - especially in the `output.json`)

**Comment by ben-moss** [comment]
@rukawata I've added the _HOTFIX_ label, as I think this breaks all existing customer deployments, unless customers update to `master` on their Terraform control machines.

**Comment by rukawata** [comment]
Hi Ben, 

The reason that you see that error is because Terraform did not pass the information under section `options` in the `input.json` to Ansible, which was the wrong behavior. This has been corrected in the same PR #286 (specifically [this part](https://github.com/Azure/sap-hana/blob/a722b72590397275595e6925b82878606f6efe15/deploy/v2/terraform/modules/output_files/main.tf)).

IMO the existing branch that are under development should merge this change from master into the local branch before continue coding. But sure we could add an additional check to validate the parameter as well - I will work on that.

The way we pass those information from `input.json` to `output.json` - which is consumed by Ansible is not the best and will be substitute with `terraform.tfstate` in the future.

Thanks,
Nancy

**Comment by ben-moss** [comment]
> IMO the existing branch that are under development should merge this change from master into the local branch before continue coding. You are right we could and should add some additional check to validate the parameter, but I do not want to add these checks everywhere. We should have a separate work item to validate all required parameters from `output.json` instead of adding checks here and there, or go with your option 2.

Thanks Nancy. To clarify the client/customer could be on `master`, but might not be tracking the latest HEAD commits due to how the code is deployed (e.g. onto a control machine that is subject to a change control procedure, or perhaps they're midway through a testing programme and this only breaks ahead of the Production deployment).

Another approach, that might satisfy more stringent release management policies would be to prevent the Runtime Instance (RTI) cloning and using the latest master repo, and instead either pass in a known version, or else copy the Terraform control machine codebase to the RTI, and execute from that.

**Comment by rukawata** [comment]
> > IMO the existing branch that are under development should merge this change from master into the local branch before continue coding. You are right we could and should add some additional check to validate the parameter, but I do not want to add these checks everywhere. We should have a separate work item to validate all required parameters from `output.json` instead of adding checks here and there, or go with your option 2.
> 
> Thanks Nancy. To clarify the client/customer could be on `master`, but might not be tracking the latest HEAD commits due to how the code is deployed (e.g. onto a control machine that is subject to a change control procedure, or perhaps they're midway through a testing programme and this only breaks ahead of the Production deployment).
> 
> Another approach, that might satisfy more stringent release management policies would be to prevent the Runtime Instance (RTI) cloning and using the latest master repo, and instead either pass in a known version, or else copy the Terraform control machine codebase to the RTI, and execute from that.

@ben-moss , make sense - I will go ahead implement the approach to copy local repo to RTI.

Thanks,
Nancy

**Comment by rukawata** [comment]
Copy local repo will not work since tfstate file is under the repo and locked. Therefore we see error: 
```
Error: Upload failed: read xxxx\sap-hana\deploy\v2\terraform\terraform.tfstate: The process cannot access the file because another process has locked a portion of the file.
```

Let's think about other options.

**Comment by rukawata** [comment]
Although we can't copy `tfstate` file over, it's possible to just copy ansible code over to RTI.
Here are the pros and cons:

Pros:

- Easy to test local ansible code changes

Cons:

- Hard for future supportability if anything goes wrong with modified ansible code

In the long run, codeline should get more stable and PaaS would be the goal, therefore we may consider keep the current way by using master clone from the repo.
In the future, it's also possible to introduce version control, so the user can switch between versions for the ansible execution.

Therefore I close this for now.

**Comment by rukawata** [comment]
We need to enable version control once v2 is complete with HA.
