### ISSUE TITLE
Error: Error running command [...] '-i '../../ansible/azure_rm.py' [...] 

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#290]
Hi, 
I have issues with single_node and ha_pair deployments. The ansible part fails with:

Error: Error running command '    OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES \
    AZURE_RESOURCE_GROUPS="HADemo" \
    [...] 
     -i '../../ansible/azure_rm.py' ../../ansible/ha_pair_playbook.yml
': exit status 4. Output:  [ERROR]: /usr/lib/python2.7/site-packages/requests/__init__.py:91:
RequestsDependencyWarning: urllib3 (1.25.6) or chardet (2.2.1) doesn't match a
supported version!   RequestsDependencyWarning)

Thanks for fixing. 
Cheers,
Michael

**Comment by rukawata** [comment]
@mimergel , can you share your tfvar file with us?

**Comment by rukawata** [comment]
The original issue no longer exists. Therefore I will close this issue.
Now we will track the problem with install packages on SLES in [SUSE bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1165732).
