### ISSUE TITLE
Backlog: Update Linux Jumpboxes to Ubuntu 18.04

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#299]
In #284 some of the Ubuntu images were updated to 18.04, but others were missed (see https://github.com/Azure/sap-hana/pull/298#discussion_r385512815).

All the images should be consistent, and there should be some form of regression test to ensure they don't drift apart following any future updates.

### Acceptance Criteria

- [ ] All references are to the same image
- [ ] Regression test added to find future config drift

**Comment by rukawata** [comment]
Currently, we have this ubuntu image defined in:
- `deploy/v2/template_samples` (samples for user)
-  `templates/tempGen` (input for azure pipeline):
```
deploy/v2/template_samples/rti_only.json:          "sku": "18.04-LTS"
deploy/v2/template_samples/single_node_hana.json:          "sku": "16.04-LTS"
deploy/v2/template_samples/nancyc.json:          "sku": "18.04-LTS"
templates/tempGen/template.json:          "sku": "18.04-LTS"
```
