### ISSUE TITLE
Capability to support Azure Availability Sets

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#301]
## Problem Statement

Prepare the Terraform code for building with High Availability in mind by building the Single Node HANA VM within an Azure Availability Set.

## Design Overview

By updating the Terraform to deploy a single HANA VM into an availability set, the future clustered VMs will also be in the availability set.

## Checklist

- [x] [V2 Documentation updated as necessary](https://github.com/Azure/sap-hana/issues/319) - See #326
- [x] Availability Set provisioned by Terraform - #318

**Comment by rukawata** [comment]
See [comment](https://github.com/Azure/sap-hana/issues/302#issuecomment-592880571). Thanks.

**Comment by peterchoo** [comment]
@rukawata Can this be closed by #318?

**Comment by rukawata** [comment]
> @rukawata ~Can this be closed by #318?~
> 
> I believe this is completed once the Documentation Update PR (#326) has been reviewed/merged in.

The only thing left is below part, which I assume should not be in the scope of current milestone.

## Design Overview

What does the interface look like?

- Deploy: `util/terraform_v2.sh apply clustered_hana`
- Destroy: `util/terraform_v2.sh destroy clustered_hana`

What input/output.json configuration changes are proposed?
