### ISSUE TITLE
Addition of Load Balancer to Single Node HANA Systems

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#302]
## Problem Statement

The current single node HANA systems built from V2 of the codebase do not have (or need) a load balancer. However, to support the scenario where a user wishes to upgrade a single node HANA system into a clustered system, we wish to add a load balancer to single node systems too.

This proposal originated from the Design Workshop, where it was stated that there is no Azure runtime cost in having a load balancer added to a single node system (or perhaps the cost is very minimal). However, adding in a load balancer into the original build, should support building out to a clustered system with negligible or no downtime.

## Design Overview

This change is unlikely to warrant any change to the interface, but may require some changes to the input/output.json configuration.

The design should support both HANA 1 and HANA 2 (from design workshop notes).

## Checklist

- [ ] V2 Documentation updated as necessary
- [ ] V2 Pipeline testing updated as necessary
- [x] Differing load balancer rules for different HANA versions should be supported
- [ ] New V2 Azure resource naming should be supported (i.e. prefixes for env details, and suffixes for resource type)
- [x] Ensure LB is configured with HANA VM (not RTI, which we used for testing)

**Comment by rukawata** [comment]
Load Balancer and Availability Set are module that can be used for HANA HA as well as NW HA setup. 
Therefore it probably makes sense to have it as its own module instead of code it as part of module `hdb_node`.
