### ISSUE TITLE
Failing to connect to hdb host 10.1.2.4 via ssh

### ISSUE THREAD

**Issue by takhoshi** [Azure/sap-hana#330]
Failing to connect to hdb host via 10.1.2.4. I can see two NICs (10.1.1.4 and 10.1.2.4) are attached to the VM hdb1 from Portal, however i am having a difficulty to connect from linux jumpbox to hdb1 via ssh. I wonder if the second NIC was correctly configured / enabled from the OS side so that the OS acknowledge all the attached NICs. BTW I didn't encounter this issue yesterday. 
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/multiple-nics

**Comment by rukawata** [comment]
Can you check the NSG rules under:
Select VM -> Settings -> Networking see if there are other rules blocking port 22, for both NICs?

Thanks,
Nancy

**Comment by takhoshi** [comment]
hi Nancy, 10.1.2.4 (hdb1-db-nic) allow any TCP inbound from 10.1.1.0/24, and anything from VNET and Loadbalancer. Meanwhile 10.1.1.4 (hdb1-admin-nic) blocks any TCP inbound with a priority of 102. 

Thanks
Taka

**Comment by rukawata** [comment]
The final fix is in PR #335.
