### ISSUE TITLE
TASK [saphana-install : run hdblcm]  Cannot resolve host name 'linux'

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#346]
Hi, deployment fails during HANA install. 

module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): TASK [saphana-install : run hdblcm] ********************************************
module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): fatal: [www-hdb0]: FAILED! => {"changed": true, "cmd": "pwd=$(<../hdbserver_WWW_passwords.xml); rm ../hdbserver_WWW_passwords.xml; echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_WWW_install.cfg' --read_password_from_stdin=xml", "delta": "0:00:01.478872", "end": "2020-03-20 09:02:46.439284", "msg": "non-zero return code", "rc": 1, "start": "2020-03-20 09:02:44.960412", "stderr": "Running in batch mode\n  Cannot resolve host name 'linux'", "stderr_lines": ["Running in batch mode", "  Cannot resolve host name 'linux'"], "stdout": "\n\nSAP HANA Lifecycle Management - SAP HANA Database 2.00.037.04.1571818940\n************************************************************************\n\n\nScanning software locations...\nDetected components:\n    SAP HANA Database (2.00.037.04.1571818940) in /hana/shared/install/SAP_HANA_DATABASE/server\nLog file written to '/var/tmp/hdb_WWW_hdblcm_install_2020-03-20_09.02.45/hdblcm.log' on host 'www-hdb0'.", "stdout_lines": ["", "", "SAP HANA Lifecycle Management - SAP HANA Database 2.00.037.04.1571818940", "************************************************************************", "", "", "Scanning software locations...", "Detected components:", "    SAP HANA Database (2.00.037.04.1571818940) in /hana/shared/install/SAP_HANA_DATABASE/server", "Log file written to '/var/tmp/hdb_WWW_hdblcm_install_2020-03-20_09.02.45/hdblcm.log' on host 'www-hdb0'."]}

Thanks for help!

**Comment by mimergel** [comment]
seems to be solved with latest repository

**Comment by rukawata** [comment]
Hi @mimergel,

This is an intermittent issue with the SLES image. We also caught that in our tests.

There is a parameter `DHCLIENT_SET_HOSTNAME` set to yes  in `/etc/sysconfig/network/dhcp` by default in the SLES image.
However this will make hostname change back and forth for a while, which leads to the failure you observed during HANA installation.

You would see in the `/var/log/messages` of the HANA server something like below:

```
2020-03-10T19:36:18.115028+00:00 hn1-hdb0 python[2215]: 2020/03/10 19:36:18.114878 INFO ExtHandler EnvMonitor: Detected hostname change: linux -> hn1-hdb0
2020-03-10T19:36:42.966259+00:00 linux python[2215]: 2020/03/10 19:36:42.966106 INFO ExtHandler EnvMonitor: Detected hostname change: hn1-hdb0 -> linux
2020-03-10T19:37:08.392443+00:00 hn1-hdb0 python[2215]: 2020/03/10 19:37:08.392322 INFO ExtHandler EnvMonitor: Detected hostname change: linux -> hn1-hdb0
2020-03-10T19:37:33.819456+00:00 linux python[2215]: 2020/03/10 19:37:33.819320 INFO ExtHandler EnvMonitor: Detected hostname change: hn1-hdb0 -> linux
2020-03-10T19:37:58.670647+00:00 hn1-hdb0 python[2215]: 2020/03/10 19:37:58.670480 INFO ExtHandler EnvMonitor: Detected hostname change: linux -> hn1-hdb0
2020-03-10T19:38:23.987351+00:00 linux python[2215]: 2020/03/10 19:38:23.987231 INFO ExtHandler EnvMonitor: Detected hostname change: hn1-hdb0 -> linux
```

We are currently working with SUSE to see if we could set this parameter to no by default in the image for Azure. Otherwise, we would manually make that change in our script.

Thanks,
Nancy

**Comment by rukawata** [comment]
Since we are working on the same issue as well, reopen the issue.

**Comment by polichtm** [comment]
I'm still seeing the same issue

module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): fatal: [hn1-hdb0]: FAILED! => {"changed": true, "cmd": "pwd=$(<../hdbserver_HN1_passwords.xml); rm ../hdbserver_HN1_passwords.xml; echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_HN1_install.cfg' --read_password_from_stdin=xml", "delta": "0:00:01.336809", "end": "2020-04-08 01:18:55.247041", "msg": "non-zero return code", "rc": 1, "start": "2020-04-08 01:18:53.910232", "stderr": "Running in batch mode\n  Cannot resolve host name 'linux': ", "stderr_lines": ["Running in batch mode", "  Cannot resolve host name 'linux':"], "stdout": "\n\nSAP HANA Lifecycle Management - SAP HANA 1.00.122.30.1582793455\n***************************************************************\n\n\nScanning Software Locations...\nDetected components:\n    SAP HANA Database (1.00.122.30.1582793455) in /hana/shared/install/SAP_HANA_DATABASE/server\nLog file written to '/var/tmp/hdb_HN1_hdblcm_install_2020-04-08_01.18.54/hdblcm.log' on host 'hn1-hdb0'.", "stdout_lines": ["", "", "SAP HANA Lifecycle Management - SAP HANA 1.00.122.30.1582793455", "***************************************************************", "", "", "Scanning Software Locations...", "Detected components:", "    SAP HANA Database (1.00.122.30.1582793455) in /hana/shared/install/SAP_HANA_DATABASE/server", "Log file written to '/var/tmp/hdb_HN1_hdblcm_install_2020-04-08_01.18.54/hdblcm.log' on host 'hn1-hdb0'."]}

pls advise
