### ISSUE TITLE
Please activate version control

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#347]
Hi, can we have version control on this repository?
This would be extremly helpful to get notified when there has been a change and also gives the possibility to use previous versions if the current version is broken.
Thanks!

**Comment by rukawata** [comment]
Hi @mimergel, 

our refactoring of the code under `sap-hana/deploy/v2` is making progress (ready for single node deployment, HA in progress). 
We will introduce version control once the v2 is ready with HA scenario, and the current code will be obsolete. 
Therefore we will not add version control to the current codeline.

Thanks for your understanding!
Nancy
