### ISSUE TITLE
Copying ini files from Primary to Secondary

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#376]
## Problem Statement:
HSR setup ideally would be a role that can be used by itself without dependency.
Therefore there could be a case where one use this role to setup HSR from an existing HANA instance where ini file has been changed.

## Enhancement:
Add task to sync (one time) ini file configuration before setting up HSR.

## Notes:
> The .ini file configuration must be similar for both systems. Any changes made manually, or by SQL commands on one system should be manually duplicated on the other system.

Source: https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/2.0.02/en-US/86267e1ed56940bb8e4a45557cee0e43.html

**Comment by robfallows** [comment]
The conventions adopted here to copy the `global.ini` file should be the same as those used for key file copying in #381.
