### ISSUE TITLE
Backlog: re-group tasks under role

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#377]
## Problem Statement:
In the current codebase, when it comes to default value, we need to define same variables repeatedly under different roles.

## Enhancement:
Tasks should be group in a level where:
1. semantically make sense
1. share some variables (eg. SID, Instance Nr, etc...)

This way, we could assign default value without duplicate effort.

**Comment by KimForss** [comment]
Ansible parts are re-written
