### ISSUE TITLE
Backlog: proper way to copy files from Primary to Secondary

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#381]
**Problem statement**
Currently we use jumpbox as media to copy files over from Primary to Secondary in
`deploy/v2/ansible/roles/hana-system-replication/tasks/copy_ssfs_keys.yml`

**Enhancement**
Find a more proper/clean way to transfer those files.

**Notes**
- With SUSE servers, we can use syncronize to push files from Primary to Secondary
- With RHEL servers, it may not be the case ([link](https://github.com/Azure/sap-hana/pull/373#discussion_r402635253))

**Dependencies**

**Checklist**

**Comment by ben-moss** [comment]
FWIW: I think the ansible `synchronize` module might not suffer the SSH trust issue by default, so could be a simple way to improve this process.

**Comment by robfallows** [comment]
Some research (for example, [here](https://www.middlewareinventory.com/blog/how-to-copy-files-between-remote-servers-ansible-fetch-sync/) - _Method 2: Copy from app01 to app02 using synchronize module_), including confirmation by testing the `synchronize` module within the role, has identified that there does need to be an explicit trust relationship between the two HANA nodes.

This relationship does not exist at the moment.

Options are:

1. Continue to use the existing method.
1. Set up a temporary (or permanent) trust between the two nodes by performing an ssh key exchange. :hand: The [process to exchange ssh public keys](https://www.middlewareinventory.com/blog/ansible-ssh-key-exchange/) is identical in principle to the current method for copying HANA keys, and so offers no advantage.

@rukawata : Continue to develop the code to use ssh key exchange or not?

**Comment by ben-moss** [comment]
1. 👍 (works and has no known/stated downsides)
2 👎 (doesn't appear to offer any security advantages)
