### ISSUE TITLE
Backlog: Simply the way we retrieve paths for HANA

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#384]
**Problem statement**
Currently, paths are semi-hard coded, eg in `deploy/v2/ansible/roles/hana-system-replication/vars/main.yml`:
`hana_instance_executable_dir: "{{ sap_dir }}/{{ sid | upper }}/HDB{{ instance_number }}/exe"`

**Enhancement**
1. Set semi-hard coded path as default.
1. Retrieve the path dynamically with sidadm for below variables:
- hana_global_dir -> cdglo
- hana_instance_executable_dir -> cdexe
- path_sys_rep_status -> cdpy
1. Set path dynamically for below variables from hana_sizes.json:
- sid_backup_dir
- hana_data_dir
- hana_backup_dir
- hana_shared_dir

**Notes**
Sample code to compose dir from hana_sizes.json ([link](https://github.com/Azure/sap-hana/pull/373#discussion_r401972159)):

```python
- name: Create dictionary with storage name and path
  set_fact:
     path_dict: "{{ path_dict | combine({item.name:item.mount_point}) }}"
  loop: "{{ hdb_sizes[hana_database.size].storage }}"
     when: item.name != 'os'
```

**Dependencies**

**Checklist**

**Comment by ben-moss** [comment]
We discussed this and agreed it was a "nice to have" feature, which can be looked at if time permits at the end of the project.
