### ISSUE TITLE
Backlog: Dynamic look for DAT/KEY file

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#385]
**Problem statement**
Currently the path to DAT/KEY files are hard-coded.

**Enhancement**
1. Set abs path for DAT/KEY file:
- hsr_dat_name
- hsr_key_name

**Notes**

1. See also related #426 

**Dependencies**

**Checklist**

**Comment by ben-moss** [comment]
Agreed as a "nice to have" feature if time permits at the end of the project, the XS requirement will move to its own "in milestone 3 scope" backlog item.
