### ISSUE TITLE
Support VM deployment with existing image

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#387]
**Is your feature request related to a problem? Please describe.**
Currently we need to specify the specs of an image.
But customer may want to provision the VM with their own image.

**Describe the solution you'd like**
Support image id in VM resource block.

**Describe alternatives you've considered**

**Additional context**

**Comment by rukawata** [comment]
## Solution

1. Add key source_image_id to os:
```
      "os": {
        "source_image_id": "",
        "publisher": "SUSE",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1"
      },
```
2. Add `source_image_id` in `azurerm_linux_virtual_machine`.
3. Change `source_image_reference` to dynamic block.

Example code:
```
  source_image_id = try(local.os.source_image_id, null)

  dynamic "source_image_reference" {
    for_each = range(try(local.os.publisher, null) == null ? 0 : 1)
    content {
      publisher = try(local.os.publisher, null)
      offer     = try(local.os.offer, null)
      sku       = try(local.os.sku, null)
      version   = try(local.os.version, null)
    }
  }
```

**Comment by KimForss** [comment]
As we spoke on IM - can we add "type" to the os section

      "os": {
        "source_image_id": "/subscriptions/80d5ed43....",
        "type": "Linux"
      },

      "os": {
        "publisher": "Oracle",
        "offer": "Oracle-Linux",
        "sku": "7.5",
        "version": "latest",
        "type": "Linux"
      },

This way we can identify if the custom image is Windows or Linux

**Comment by rukawata** [comment]
Sure, since HANA only supports Linux so the os type is not needed.
But I see your point to have that for anydb.
I would propose below structure and let me know if that works for you :)

 ```
 "os": {
    "source_image_id": "/subscriptions/80d5ed43....",  <<---- If provided, overwrites publisher, offer, sku, version.
    "os_type": "Linux"
    "publisher": "Oracle",
    "offer": "Oracle-Linux",
    "sku": "7.5",
    "version": "latest"
  },
```

**Comment by KimForss** [comment]
This should be for App tier as well as quite a few customers have Windows App Servers

The structure below works for me
