### ISSUE TITLE
[BUG] Single node deployment fails with Cannot resolve host name 'linux' error message

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#389]
A single node deployment option fails with the error message  Cannot resolve host name 'linux' error message during TASK [saphana-install : run hdblcm] task (symptoms match #346)

module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): TASK [saphana-install : run hdblcm] ********************************************
module.configure_vm.null_resource.mount-disks-and-configure-hana (local-exec): fatal: [hn1-hdb0]: FAILED! => {"changed": true, "cmd": "pwd=$(<../hdbserver_HN1_passwords.xml); rm ../hdbserver_HN1_passwords.xml; echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_HN1_install.cfg' --read_password_from_stdin=xml", "delta": "0:00:01.336809", "end": "2020-04-08 01:18:55.247041", "msg": "non-zero return code", "rc": 1, "start": "2020-04-08 01:18:53.910232", "stderr": "Running in batch mode\n  Cannot resolve host name 'linux': ", "stderr_lines": ["Running in batch mode", "  Cannot resolve host name 'linux':"], "stdout": "\n\nSAP HANA Lifecycle Management - SAP HANA 1.00.122.30.1582793455\n***************************************************************\n\n\nScanning Software Locations...\nDetected components:\n    SAP HANA Database (1.00.122.30.1582793455) in /hana/shared/install/SAP_HANA_DATABASE/server\nLog file written to '/var/tmp/hdb_HN1_hdblcm_install_2020-04-08_01.18.54/hdblcm.log' on host 'hn1-hdb0'.", "stdout_lines": ["", "", "SAP HANA Lifecycle Management - SAP HANA 1.00.122.30.1582793455", "***************************************************************", "", "", "Scanning Software Locations...", "Detected components:", "    SAP HANA Database (1.00.122.30.1582793455) in /hana/shared/install/SAP_HANA_DATABASE/server", "Log file written to '/var/tmp/hdb_HN1_hdblcm_install_2020-04-08_01.18.54/hdblcm.log' on host 'hn1-hdb0'."]}

**Comment by rukawata** [comment]
Hi,

The problem you are facing the a result of waagent not setting up hostname in a stable way. So it's an intermittent issue.
For this there is a [fixed](https://github.com/Azure/WALinuxAgent/pull/1832) from SLES that will be included in their next image release.

Before we get the fix from SLES, one could logon to the HANA server VM, manually change the hostname with `hostnamectl set-hostname <hostname>`, then rerun the ansible-playbook in command line. This would be less effort than rerun the deployment.

Hope this helps!

Thanks,
Nancy
