### ISSUE TITLE
[BUG] NSG misconfiguration for the Windows bastion host causes HA deployment to fail

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#394]
I'm seeing the following when including the Windows bastion host in the HA deployment. 

fatal: [hn1-win-bastion]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPSConnectionPool(host='52.170.156.12', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f290390d490>, 'Connectionto 52.170.156.12 timed out. (connect timeout=30)'))", "unreachable": true}

It appears that the NSG associated with the subnet where the Windows host resides does not include RDP/winrm rules
rgds
Marcin

**Comment by rukawata** [comment]
Hi @polichtm, can you provide more details as regarding how to reproduce this issue? For example an example of the tfvar you used could be helpful (you can mask the sensitive information).

**Comment by polichtm** [comment]
Hi @rukawata 
Certainly - it's the same tfvar I provided for #395 except in this one I included provisioning of the Windows bastion host:
Steps to reproduce
clone the repo
cd ~/sap-hana/deploy/vm/modules/ha_pair/
create terraform.tfvars with the following settings
az_region = "eastus"
az_resource_group = "hanav1ha-RG"
az_domain_name = "-------------"
vm_size = "Standard_E8s_v3"
sshkey_path_public = "/.ssh/id_rsa.pub"
sshkey_path_private = "/.ssh/id_rsa"
vm_user = "labuser"
sap_sid = "HN1"
sap_instancenum = "01"
url_sap_sapcar_linux = "https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000935.EXE"
url_sapcar_windows = "https://---------------------------.blob.core.windows.net/sapbits/SAPCAR_1311-80000938.EXE"
url_sap_hdbserver = "https://---------------------------.blob.core.windows.net/sapbits/IMDB_SERVER100_122_30-10009569.SAR"
url_hana_studio_windows = "https://---------------------------.blob.core.windows.net/sapbits/IMC_STUDIO2_122_30-80000323.SAR"
pw_os_sapadm = "---------------------------"
pw_os_sidadm = "---------------------------"
pw_db_system = "---------------------------"
pwd_db_xsaadmin = "---------------------------"
pwd_db_tenant = "---------------------------"
pwd_db_shine = "---------------------------"
email_shine = "shine@emailaddress.com"
useHana2 = false
install_xsa = false
install_shine = false
install_cockpit = false
install_webide = false
hdb_mdc = false
hana1_db_mode = "single_container"
windows_bastion = true
pw_bastion_windows = "---------------------------"
pw_hacluster = "---------------------------"
terraform init/plan/apply

Pls let me know if any additional clarification is needed

rgds
Marcin

**Comment by rukawata** [comment]
@polichtm, the issue has been fixed.

**Comment by polichtm** [comment]
excellent - thnx
