### ISSUE TITLE
[BUG] Occasional failure of tasks which escalate privilege

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#410]
**Describe the bug**
Sometimes, the playbook fail at step to ensure replication status is active:

```
FAILED - RETRYING: Ensure replication status is active (1 retries left).
fatal: [10.1.1.4]: FAILED! => {"attempts": 30, "changed": false, "cmd": "source ~/.bashrc ; python /usr/sap/HN1/HDB00/exe/python_support/systemReplicationStatus.py | grep -q 'overall system replication status: ACTIVE'\n", "delta": "0:00:00.984375", "end": "2020-04-14 15:54:15.427080", "msg": "non-zero return code", "rc": 1, "start": "2020-04-14 15:54:14.442705", "stderr": "tset: standard error: Inappropriate ioctl for device", "stderr_lines": ["tset: standard error: Inappropriate ioctl for device"], "stdout": "", "stdout_lines": []}
```

**To reproduce**
Observed in pipeline:
https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=2987&view=logs&j=fbfe0e49-2635-5f04-67d5-c37d2a53bced&t=383784f4-54a8-5074-c666-fbda20b56f76

**Expected behavior**
If it is a timing issue, let's improve the retry logic.

**Additional context**
NA

**Possible Fixes**

- Try `any_errors_fatal: true` option (and related options): https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-the-play

**Comment by robfallows** [comment]
Further to the Teams convo: https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=2987&view=logs&j=fbfe0e49-2635-5f04-67d5-c37d2a53bced&t=383784f4-54a8-5074-c666-fbda20b56f76&l=351

**Comment by rukawata** [comment]
@robfallows: is this the link you are referring to? https://dev.azure.com/azuresaphana/Azure-SAP-HANA/_build/results?buildId=2987&view=logs&j=fbfe0e49-2635-5f04-67d5-c37d2a53bced&t=383784f4-54a8-5074-c666-fbda20b56f76

**Comment by robfallows** [comment]
@rukawata : sort of. The link I posted went straight to the Ansible output line with the error, which was this task: <https://github.com/Azure/sap-hana/blob/df872c8810d92f4dfb57ed568e197d60e3de0319/deploy/v2/ansible/roles/components-install/tasks/hana_database.yml#L23-L27>

**Comment by rukawata** [comment]
The HANA installation failed on secondary node and that's why we see the error:

```
TASK [components-install : Create install template for SAP HANA 2.0] ***********
changed: [10.1.1.4]
fatal: [10.1.1.5]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```

**Comment by robfallows** [comment]
@rukawata : suggest the title of this bug is incorrect.
