### ISSUE TITLE
Capability to switch OS image type (SLES/RHEL) in input JSON templates

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#423]
## Problem Statement

In order to provision and configure deployments which are built with either SLES or Red Hat, there needs to be a more convenient way to specify the required OS than a manual edit of the `input.json`.

## Enhancement

Implement a new `util/set_sap_os.sh` script which can work with multiple templates by allowing the target template to be specified on the command line. This follows the existing behaviour of the `util/terraform_v2.sh` script, such that:

When the user runs `util/set_sap_os.sh <SAP OS> <target template>`
Then the script:
- [ ] Sets the correct OS `publisher`, `offer` and `sku` in the given template.
- [ ] Fails with a suitable error when no target template is provided or the given template does not exist
- [ ] Fails with a suitable error when an invalid `<SAP OS>` is provided.
- [ ] When a non-valid set of inputs is provided, the script should provide a list of valid `<SAP OS>` and `<target templates>` based on those available in the templates dir, and filters the list to those containing `hana`. For example:

  ```text
  Where <SAP OS> is one of the following:
  - SLES (case insensitive)
  - RedHat (case insensitive)

  Where <target template> is one of the following:
  - clustered_hana
  - single_node_hana
  ```

## Notes

1. To aid future refactoring the code should follow the patterns and conventions already laid out for similar functionality in `terraform_v2.sh`.
1. Some valid sets of inputs are:
   - `util/set_sap_os.sh "redhat" single_node_hana`
   - `util/set_sap_os.sh "sles" clustered_hana`
1. Some invalid sets of inputs are:
   - `util/set_sap_os.sh single_node_hana`
   - `util/set_sap_os.sh redhat`

## Dependencies

None

## Future Work

It's possible to specify variations of `offer` and `sku` for each operating system. The initial implementation will use the existing values for SLES and for Red Hat will use `"offer": "RHEL-SAP-HA"` and `"sku": "76sapha-gen2"`.

## Checklist

- [ ] Usage documentation updated as necessary
- [ ] Architecture documentation updated as necessary

## References

- [PR for similar previous behaviour in `terraform_v2.sh`](https://github.com/Azure/sap-hana/pull/298)

**Comment by rukawata** [comment]
To switch between SLES/RHEL, this [part](https://github.com/Azure/sap-hana/blob/5168f6e7105b3a97f87c67382373c4487f250f25/deploy/v2/template_samples/single_node_hana.json#L118-L120) in input JSON can do the job :)
