### ISSUE TITLE
Move all service principal scripts into `util` directory

### ISSUE THREAD

**Issue by ben-moss** [Azure/sap-hana#427]
**Problem statement**

From the review of #421, the preference for where all the generated/documented service principal scripts are stored should move away from the project root directory into the `util` directory.

**Enhancement**

Update the following to reflect the preference that all service principal scripts should be stored in the `util` directory:
- Scripts
- Docs (V1 and V2 READMEs and V2 USAGE)
- Terraform (and maybe ansible?)

**Notes**

1. This may impact current users of V1 README/process

**Dependencies**

- None

**Checklist**

- [ ] Docs updated
- [ ] Terraform/ansible updated
- [ ] Scripts updated
- [ ] Scripts / process tested in line with the new docs

**Comment by peterchoo** [comment]
The script file output from this command should be placed in the Terraform Workspace directory, relative to where the script is run from.  This is to align with the documentation updates recommending workspace folders to separate logical concerns, and the use of terraform workspaces for the generated inventory and output.json files.
