### ISSUE TITLE
Backlog: Use ansible facts when possible instead of JSON

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#464]
**Problem statement**
Things like IP address are currently pulled from output.JSON

**Enhancement**
Those are facts of the ansible target machine. Pull that info from ansible facts instead.

**Notes**
Example: https://github.com/Azure/sap-hana/pull/459#discussion_r418549708

**Dependencies**

**Checklist**

**Comment by ben-moss** [comment]
I'm not clear on this idea from the given example.
My understanding of the example is in relation to a cluster.
Let's say the cluster has two nodes - A and B.
I believe the code says: When running on node B, then copy a file from node A's IP.
Wouldn't the fact for running on node B return B's IP address? However, it's A's IP that's needed for ansible delegation.

However, I can see some value in refactoring this code to reduce coupling and dependency on the output JSON. This would involve:
1. Creating role default variables for the IPs of each node in the cluster (or a list to handle the more complex future case of > 2 nodes);
1. Replacing the current output JSON IP references with the default variables;
1. Calling the role with the output JSON IP references to set the defaults.

**Comment by rukawata** [comment]
You are right. The underlying thinking is to have less dependency on output.JSON if possible (also to guarantee the host info are correct and up to date), and will be our goal in the future.

Instead of replacing IP in the JSON - which makes it still relying on the output.JSON, would it make more sense to just store them in variables and use them for later on?

**Comment by ben-moss** [comment]
The ansible role could be decoupled from the output JSON using the process I described above. This improves the role's reusability, but doesn't solve the system's overall dependency on output JSON. To solve that would be a more significant refactor - probably looking at a rework of the overall design and permeating the Terraform and Ansible layers - beyond the scope of this project, but one for the longer-term roadmap.

I suggest either making this issue about the role refactor, and keeping it in the project scope, or else making it about the wider design change and moving it out of the project's scope.

**Comment by rukawata** [comment]
Agree. The goal in this issue should not be removing dependency on output JSON completely. 
Role refactor is fine. Thanks!
