### ISSUE TITLE
Deployment of HA SAP-HANA into existing VNETs & SUBNETs

### ISSUE THREAD

**Issue by mimergel** [Azure/sap-hana#503]
Hi, Can you add the possibility to deploy into existing VNETs & SUBNETs? This is from my perspective a mandatory feature in real life customer scenarios. If this is already possible then at least I'm missing a description somewhere how this can be realized. 
Thanks,
Michael

**Comment by rukawata** [comment]
The fix has been merged and you can find a sample here: https://github.com/Azure/sap-hana/blob/master/deploy/template_samples/clustered_hana_with_sbd_in_existing_subnet.json

Thanks,
Nancy
