### ISSUE TITLE
Top Level Items

### ISSUE THREAD

**Issue by robfallows** [Azure/sap-hana#504]
# Enhancement

## Problem statement

This Sprint is to structure a complete SAP deployment of IaaS (excluding NFS) and make it independently modular.

## Notes

Deploy:

- Common components
  - HANA Tier True/False #506
  - AP Application Tier True/False #507
- The SAP Application Tier:
  - SCS (SA/HA) #509 #510
  - APP Instance (1 or more)

## Checklist

  - [x] HANA Tier True/False
  - [x] SAP Application Tier True/False
  - [x] SCS (SA/HA) Red Hat
    - [x] Single node
    - [x] HA pair
  - [x] SCS (SA/HA) SUSE
    - [x] Single node
    - [x] HA pair
  - [x] APP Instance (1 or more) Red Hat
  - [x] APP Instance (1 or more) SUSE
  - [x] Update Inventory generation with Application Tier

**Comment by ben-moss** [comment]
All this work's now been completed with related PRs merged, so this completes the two project milestones. Pete will be finishing off the agreed project backlog work over the next few days.

I'll close this tracking issue now.
