### ISSUE TITLE
Terraform: Application Tier VM and Disk Sizing

### ISSUE THREAD

**Issue by peterchoo** [Azure/sap-hana#517]
# Problem statement

There is no specification for the Application Tier VMs.  #515 has assumed a `Standard_D4a_v4` will be sufficient.  This is currently ailing pipelines tests due to quota restrictions.

## Required Information

For both the SCS/ERS, and the Application VMs

1. VM Size(s) - will there only be one, or will there be a t-shirt size list of sizes to pick?
1. OS disk type and size(s) - t-shirt size list?
1. Additional Data disks?
   1. If so, sizings?

**Comment by rukawata** [comment]
As discussed, in this issue we will focus on:
1. implement a sizing json like `hdb_sizes.json`
1. make it as flexible as possible.
1. only one size (naming like "Demo", "Default", etc...) in the size json.
