### ISSUE TITLE
[BUG]Ansible playbook fails for SAP HANA package downloads

### ISSUE THREAD

**Issue by ranaanimesh** [Azure/sap-hana#573]
**Describe the bug**
While running the Ansible Playbook from Ansible-jumpbox, I run into the following error during SAP Media download stage:-
TASK [sap-media-download : Download installation media] *********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "python3 /home/azureadm/sap-hana/deploy/ansible/../python/downloader/basket.py --config /home/azureadm/output.json --dir /sapmnt", "delta": "0:00:02.000656", "end":"2020-06-19 22:23:55.520045", "msg": "non-zero return code", "rc": 1, "start": "2020-06-19 22:23:53.519389", "stderr": "Traceback (most recent call last):\n  File \"/home/azureadm/sap-hana/deploy/ansible/../python/downloader/basket.py\", line 43, in <module>\n    SMP.init()\n  File \"/home/azureadm/sap-hana/deploy/python/downloader/SAP_SMP.py\", line 157, in init\n    \"authenticity_token\": inputs_sso[\"authenticity_token\"],\n  File \"/home/azureadm/sap-hana/deploy/python/downloader/SAP_SMP.py\", line 65, in process_page\n    \"%s inputs (%s) does not contain required fields (%s)\" % (desc, inputs, required_inputs)\nAssertionError: obtain SAML responseinputs ({'mobileSSOToken': '', 'sourceUrl': '', 'SAMLRequest': 'PEF1dGhuUmVxdWVzdCB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczpuczI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIHhtbG5zOm5zMz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyIgeG1sbnM6bnM0PSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyMiIERlc3RpbmF0aW9uPSJodHRwczovL2FjY291bnRzLnNhcC5jb20vc2FtbDIvaWRwL3NzbyIgRm9yY2VBdXRobj0iZmFsc2UiIElEPSJTMGU1ODNiYzctMjQ5Yy00M2RiLWFmOTctZTJiNTJjZmEzNDQxLXZ1TmNraFNfTW92cUZ1dHZiTUE2VS5xYXZwazY3OTd4dHdCcnpwcGRSNW8iIElzc3VlSW5zdGFudD0iMjAyMC0wNi0xOVQyMjoyMzo1NC41MzZaIiBWZXJzaW9uPSIyLjAiPjxuczI6SXNzdWVyPmh0dHBzOi8vaGFuYS5vbmRlbWFuZC5jb20vc3VwcG9ydHBvcnRhbDwvbnMyOklzc3Vlcj48ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj48ZHM6U2lnbmVkSW5mbz48ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz48ZHM6UmVmZXJlbmNlIFVSST0iI1MwZTU4M2JjNy0yNDljLTQzZGItYWY5Ny1lMmI1MmNmYTM0NDEtdnVOY2toU19Nb3ZxRnV0dmJNQTZVLnFhdnBrNjc5N3h0d0JyenBwZFI1byI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3NoYTEiLz48ZHM6RGlnZXN0VmFsdWU+dytOK3JrNGxDSHBEOGkyVXZwbDJMSjdzMmZRPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPjxkczpTaWduYXR1cmVWYWx1ZT5PUUJiMFI2dkh5Z2pnckxlVXZnbCtNb0R2ZTFUTXR5UVI2cVdZRmNUMGdVN2FmQ3FkVFh6TWtqc2VUdFZ2d08vUUtIL0UzdzlwOU9VbXMwVkI0UnpEWTJQS2Nlb3M5bGtBRkNpeU9TazlKRisyZlg4MzB2UkxYRjhGVWdMcGY3MjROM0ZDRjVyOUtpL29VeWs3dDlvdklreVd5U20zWjkvZ0EzZVJ4bnh3R1lSQnZwZ0dmUlJMNWlaYUdyWm9iK2JvVElTWVhXdks4d3FSZmtibFhtRTAwVStvQTBZMmQ0K0dYY0YxeGVhcGNaZlMybVlJNlZwYWRvN2Urem5FaUdBTkxpSGZPVDI0MGtZeDRGYmFqOHlRUnJSNWVsMmxLSksxdmFCT1VVMG5HWUtRK2NHVjVoRDd4MGFnSmZrTGl3U1JZOE1uc2NZRTYwTnhKTUxuaE9ISUE9PTwvZHM6U2lnbmF0dXJlVmFsdWU+PC9kczpTaWduYXR1cmU+PC9BdXRoblJlcXVlc3Q+', 'tfaToken': '', 'idpSSOEndpoint': 'https://accounts.sap.com/saml2/idp/sso', 'j_username': None, 'RelayState': 'oucrsmdmqwjyhvucsxswtuyys', 'method': 'POST', 'targetUrl': 'https://launchpad.support.sap.com/', 'css': '', 'authenticity_token': 'ScctXWPgfcQgBFIZ2dfPDGzX9JABGqPjcgVNrI2mXWeFqraGA7FsPd2jyhTPYGdlapoEC4Nl5ikijQTjiq3XKg==', 'utf8': '✓', 'spId': '55365985e4b07dc3abdfc16c', 'spName': 'https://hana.ondemand.com/supportportal', 'org': '', 'xsrfProtection': 'Au+/vXx1V++/ve+/vQ3vv73vv704Sww3Ce+/vRp777+9Pe+/vX7vv700Je+/vUPvv71177+977+9bDoxNTkyNjA1NDM1MTkw'}) does not contain required fields (['SAMLResponse'])", "stderr_lines": ["Traceback (most recent call last):", "  File \"/home/azureadm/sap-hana/deploy/ansible/../python/downloader/basket.py\", line 43, in <module>", "    SMP.init()", "  File \"/home/azureadm/sap-hana/deploy/python/downloader/SAP_SMP.py\", line 157, in init", "    \"authenticity_token\": inputs_sso[\"authenticity_token\"],", "  File \"/home/azureadm/sap-hana/deploy/python/downloader/SAP_SMP.py\", line 65, in process_page", "    \"%s inputs (%s) does not contain required fields (%s)\" % (desc, inputs, required_inputs)", "AssertionError: obtain SAML response inputs ({'mobileSSOToken': '', 'sourceUrl': '', 'SAMLRequest': 'PEF1dGhuUmVxdWVzdCB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczpuczI9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIHhtbG5zOm5zMz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyIgeG1sbnM6bnM0PSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyMiIERlc3RpbmF0aW9uPSJodHRwczovL2FjY291bnRzLnNhcC5jb20vc2FtbDIvaWRwL3NzbyIgRm9yY2VBdXRobj0iZmFsc2UiIElEPSJTMGU1ODNiYzctMjQ5Yy00M2RiLWFmOTctZTJiNTJjZmEzNDQxLXZ1TmNraFNfTW92cUZ1dHZiTUE2VS5xYXZwazY3OTd4dHdCcnpwcGRSNW8iIElzc3VlSW5zdGFudD0iMjAyMC0wNi0xOVQyMjoyMzo1NC41MzZaIiBWZXJzaW9uPSIyLjAiPjxuczI6SXNzdWVyPmh0dHBzOi8vaGFuYS5vbmRlbWFuZC5jb20vc3VwcG9ydHBvcnRhbDwvbnMyOklzc3Vlcj48ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj48ZHM6U2lnbmVkSW5mbz48ZHM6Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz48ZHM6UmVmZXJlbmNlIFVSST0iI1MwZTU4M2JjNy0yNDljLTQzZGItYWY5Ny1lMmI1MmNmYTM0NDEtdnVOY2toU19Nb3ZxRnV0dmJNQTZVLnFhdnBrNjc5N3h0d0JyenBwZFI1byI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3NoYTEiLz48ZHM6RGlnZXN0VmFsdWU+dytOK3JrNGxDSHBEOGkyVXZwbDJMSjdzMmZRPTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPjxkczpTaWduYXR1cmVWYWx1ZT5PUUJiMFI2dkh5Z2pnckxlVXZnbCtNb0R2ZTFUTXR5UVI2cVdZRmNUMGdVN2FmQ3FkVFh6TWtqc2VUdFZ2d08vUUtIL0UzdzlwOU9VbXMwVkI0UnpEWTJQS2Nlb3M5bGtBRkNpeU9TazlKRisyZlg4MzB2UkxYRjhGVWdMcGY3MjROM0ZDRjVyOUtpL29VeWs3dDlvdklreVd5U20zWjkvZ0EzZVJ4bnh3R1lSQnZwZ0dmUlJMNWlaYUdyWm9iK2JvVElTWVhXdks4d3FSZmtibFhtRTAwVStvQTBZMmQ0K0dYY0YxeGVhcGNaZlMybVlJNlZwYWRvN2Urem5FaUdBTkxpSGZPVDI0MGtZeDRGYmFqOHlRUnJSNWVsMmxLSksxdmFCT1VVMG5HWUtRK2NHVjVoRDd4MGFnSmZrTGl3U1JZOE1uc2NZRTYwTnhKTUxuaE9ISUE9PTwvZHM6U2lnbmF0dXJlVmFsdWU+PC9kczpTaWduYXR1cmU+PC9BdXRoblJlcXVlc3Q+', 'tfaToken': '', 'idpSSOEndpoint': 'https://accounts.sap.com/saml2/idp/sso', 'j_username': None, 'RelayState': 'oucrsmdmqwjyhvucsxswtuyys', 'method': 'POST', 'targetUrl': 'https://launchpad.support.sap.com/', 'css': '', 'authenticity_token': 'ScctXWPgfcQgBFIZ2dfPDGzX9JABGqPjcgVNrI2mXWeFqraGA7FsPd2jyhTPYGdlapoEC4Nl5ikijQTjiq3XKg==', 'utf8': '✓', 'spId': '55365985e4b07dc3abdfc16c', 'spName': 'https://hana.ondemand.com/supportportal', 'org': '', 'xsrfProtection': 'Au+/vXx1V++/ve+/vQ3vv73vv704Sww3Ce+/vRp777+9Pe+/vX7vv700Je+/vUPvv71177+977+9bDoxNTkyNjA1NDM1MTkw'}) does not contain required fields (['SAMLResponse'])"], "stdout": "", "stdout_lines": []}

**To reproduce**
1. Follow the instructions listed in https://github.com/Azure/sap-hana/blob/master/deploy/terraform/HANA.md to 
	a) initialize deployment workspace
	b) adjusting the templates - I am using the single_node_hana.json (https://github.com/Azure/sap-hana/blob/master/deploy/template_samples/single_node_hana.json) 
	c) running the terraform deployment using the single_node_hana.json
	d) running ansible playbook - After logging to the Ansible jump box, Run the suggested command ‘ansible-playbook -i hosts.yml ~/sap-hana/deploy/ansible/sap_playbook.yml’

2. See error

**Expected behavior**
Ansible Playbook should download and install the SAP packages on RTI, APP and DB.

**Additional context**
Feel free to contact me if triage is needed to debug the issue.

**Comment by rukawata** [comment]
Hi @ranaanimesh,

Can you double check if you have filled your SAP credentials to download SAP software in the template ([here](https://github.com/Azure/sap-hana/blob/d386ba9493046e3b77450ffd600184f52d35ad87/deploy/template_samples/single_node_hana.json#L210-L211))?

Since we do not distribute or store SAP media, you will have to provide those information so the script will trigger the software download from SMP.

Hope it helps!

Thanks,
Nancy

**Comment by ranaanimesh** [comment]
Thanks for replying back. Is the SAP user id and password listed on https://github.com/microsoft/sap-hana/blob/master/deploy/USAGE.md#summary a valid credential that can be used in the template?

**Comment by rukawata** [comment]
> Thanks for replying back. Is the SAP user id and password listed on https://github.com/microsoft/sap-hana/blob/master/deploy/USAGE.md#summary a valid credential that can be used in the template?

No, that is just an example but not a valid SAP user (S-user).
Here is a [article](https://www.sapanalytics.cloud/resources-s-user-id/) to explain what is S-user, hope it helps.

**Comment by rukawata** [comment]
Close as it's invalid.
