### ISSUE TITLE
Terraform: AnyDB VM and Disk Sizing

### ISSUE THREAD

**Issue by rukawata** [Azure/sap-hana#580]
Please refer to #517.
Same requirement but for AnyDB.

**Comment by KimForss** [comment]
Why do we need a separate json for this? I solved the same using map files.

Can we use the json file in Terraform enterprise?

**Comment by rukawata** [comment]
Yes, it will work with Terraform Cloud and Enterprise.
This is a static json file that reads into TF once.

**Comment by KimForss** [comment]
Json file added for anydb
