### ISSUE TITLE
Single node case is broken with addition of service principal

### ISSUE THREAD

**Issue by pabowers** [Azure/sap-hana#70]
Error: module "configure_vm": missing required argument "azure_service_principal_id"

Error: module "configure_vm": missing required argument "azure_service_principal_pw"

**Comment by persiaAziz** [comment]
Yah it is expected, These are global required variables now, so even though single node does not use it, it needs to be passed. Also this is required for configuration of Ansible and terraform for the deployment anyway

**Comment by persiaAziz** [comment]
PR: https://github.com/Azure/sap-hana/pull/71
