### ISSUE TITLE
Phase 1 scope

### ISSUE THREAD

**Issue by YunziZhangAzure** [Azure/sap-hana#717]
### Goal
This doc is to describe the scope of phase 1

### Workflow

**Step 1 – Bootstrap SAP_DEPLOYER** 

**Workflow:** 

- Azure Portal – Cloud Shell 
- Ensure correct Default Subscription 
- mkdir ~/azure_sap_automated_deployment; cd $_ 
- git clone https://github.com/Azure/sap-hana.git 
- cd sap-hana; git checkout feature/remote-tfstate 
- mkdir -p ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure; cd $_ 
- ssh-keygen -q -t rsa -C "Deploy Platform" -f sshkey 
- vi np-scus-deployer-infrastructure.json 
```
{ 

  "infrastructure": { 

    "region": "southcentralus", 

    "resource_group": { 

      "name" : " np-scus-deployer-infrastructure " 

    }, 

    "vnets": { 

      "management": { 

        "name" : "np-scus-deployer-vnet", 

        "address_space" : "10.0.0.0/26", 

        "subnet_mgmt": { 

          "name" : " np-scus-deployer_deployment-subnet", 

          "prefix" : "10.0.0.16/28", 

          "nsg": { 

            "name" : "np-scus-deployer_deployment-nsg" 

          } 

        } 

      } 

    } 

  }, 

  "sshkey": { 

    "path_to_public_key": "sshkey.pub", 

    "path_to_private_key": "sshkey" 

  }, 

  "options": { 

    "enable_secure_transfer": true 

  } 
```
Under ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure, manually run the following commands: 

- terraform init ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/ 
- terraform plan -var-file=np-scus-deployer-infrastructure.json ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/ 
- terraform apply -auto-approve -var-file=np-scus-deployer-infrastructure.json  ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/ 

_zip, git, terraform and other essential tools will be installed on deployer._ 
_azure_sap_automated_deployment and workspaces structure will be created_ 
_Repo will be cloned into ~/azure_sap_automated_deployment_ 
_post_deployment.sh will be generated under ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure/._ 
_This script is used to upload deployer’s terraform.tfstate, ssh key pair(private & public key), np-scus-deployer-infrastructure.json to the primary deployer under its ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure_
- Run post_deployment.sh 

**Notes:** 

Azure management lock is not within the scope 

**Step 2 – Bootstrap SAP_LIBRARY** 

**Workflow:** 

Log on to newly deployed deployer

- cd ~/azure_sap_automated_deployment/sap-hana && git checkout feature/remote-tfstate 
- mkdir -p ~/azure_sap_automated_deployment/workspaces/sap_library/np-scus-sap_library; cd $_ 
- vi np-scus-sap_library.json 
```
{ 
  "infrastructure": { 
      "region": "southcentralUS", 
      "resource_group": { 
          "name": "np-scus-sap_library" 
      } 
  }, 
  "storage_account_sapbits": { 

      "file_share": { 

          "enable_deployment": true, 

          "name": "sapbits" 

      }, 

      "sapbits_blob_container": { 

          "enable_deployment": true, 

          "name": "sapbits" 

      } 
  }, 

  "storage_account_tfstate": { 

      "saplibrary_blob_container": {}

  } 
} 
```

Under ~/azure_sap_automated_deployment /workspaces/sap_library/np-scus-sap_library, manually run the following commands: 
- terraform init ../../../sap-hana/deploy/terraform/bootstrap/sap_library/ 
- terraform plan -var-file=np-scus-sap_library.json ../../../sap-hana/deploy/terraform/bootstrap/sap_library 
- terraform apply -auto-approve -var-file=np-scus-sap_library.json ../../../sap-hana/deploy/terraform/bootstrap/sap_library/ 

_terraform.tfstate will be generated under current folder._ 
_Only one container will be provisioned. All terraform.tfstate files will be uploaded there._  

**Step 3 – Re-Initialize SAP_LIBRARY**  

**Workflow**

Under ~/azure_sap_automated_deployment /workspaces/sap_library/np-scus-sap_library/, manually run the following commands: 
- terraform output {tfstate_sa_name} 
- terraform init --force-copy                                                        \ 
               --backend-config "resource_group_name=np-scus-sap_library"    \ 
               --backend-config "storage_account_name=tfstate187c37f9"            \ 
               --backend-config "container_name=saplibrary"                        \ 
               --backend-config "key=np-scus-sap_library.terraform.tfstate"  \ 
               ../../../sap-hana/deploy/terraform/run/sap_library/ 
- terraform plan                                                                      \ 
                -var-file=np-scus-sap_library.json                           \ 
                ../../../sap-hana/deploy/terraform/run/sap_library  
- terraform apply                                                                     \ 
       	    -auto-approve --var-file=np-scus-sap_library.json            \ 
                ../../../sap-hana/deploy/terraform/run/sap_library/ 

**Step 4 – Re-Initialize SAP_DEPLOYER**

**Workflow** 

Under ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure/, run the following commands: 

- terraform init --force-copy                                                         \ 
               --backend-config "resource_group_name=np-scus-sap_library"     \ 
               --backend-config "storage_account_name=tfstate187c37f9"              \ 
               --backend-config "container_name=saplibrary"                         \ 
               --backend-config "key=np-scus-deployer-infrastructure.terraform.tfstate"  \ 
               ../../../sap-hana/deploy/terraform/run/sap_deployer/ 
- terraform plan                                                                       \ 
                -var-file=np-scus-deployer-infrastructure.json                \ 
                ../../../sap-hana/deploy/terraform/run/sap_deployer/ 
- terraform apply --auto-approve                                                       \ 
                -var-file=np-scus-deployer-infrastructure.json                \ 
                ../../../sap-hana/deploy/terraform/run/sap_deployer/ 

**Expected Results:**
The tfstate file np-scus-deployer-infrastructure.terraform.tfstate is migrated to the remote location 

**Step 5 – SAP_SYSTEM – Create Network Only** 

**Workflow:**

On deployer,
- mkdir -p ~/azure_sap_automated_deployment/workspaces/sap_landscape/np-scus-sap0-infrastructure; cd $_ 
- vi np-scus-sap0-infrastructure.json 
```
{ 

  "infrastructure": { 

    "landscape": "SAP0", 

    "region": "southcentralus", 

    "resource_group": { 

      "name": "np-scus-sap0-infrastructure" 

    }, 

    "vnets": { 

      "sap": { 

        "name": "np-scus-sap0-vnet", 

        "address_space": "10.1.0.0/16", 

        "subnet_iscsi": { 

          "name": " np-scus-sap0_iscsi-subnet", 

          "prefix": "10.1.0.0/24" 

        } 

      } 

    } 

  }, 

  "jumpboxes": { 

    "windows": [], 

    "linux": [] 

  }, 

  "databases": [ { "platform"         : "NONE" } ], 

  "application": { "enable_deployment": false  }, 

  "software": { }, 

  "sshkey": { }, 

  "options": { } 

} 
```

- cp ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure/sshkey* . 

- Fetch resource group name, storage account name, container name, there are several ways to do this, eg: 

egrep -wi 'resource_group_name|storage_account_name|container_name' ../../local/np-scus-deployer-infrastructure/.terraform/terraform.tfstate 

Under ~/azure_sap_automated_deployment/workspaces/sap_landscape/np-scus-sap0-infrastructure/, run the following commands: 
- terraform init                                                                      \ 
               --backend-config "resource_group_name= np-scus-sap_library"     \ 
               --backend-config "storage_account_name=tfstate187c37f9"              \ 
               --backend-config "container_name=saplibrary"                         \ 
               --backend-config "key=np-scus-sap0-infrastructure.terraform.tfstate"      \ 
               ../../../sap-hana/deploy/terraform/run/sap_system/ 
- terraform plan                                                                      \ 
                -var-file=np-scus-sap0-infrastructure.json                   \ 
                ../../../sap-hana/deploy/terraform/run/sap_system/ 
- terraform apply --auto-approve                                                      \ 
                -var-file=np-scus-sap0-infrastructure.json                   \ 
                ../../../sap-hana/deploy/terraform/run/sap_system/ 

**Expected Results:** 
Successful deployment and peering of only workload VNET 

**Notes:** 
In phase 1, sap_system module is used to provision sap landscape 
 

**Step 6 – SAP_SYSTEM - SID** 

**Workflow:**

On deployer,
- mkdir -p ~/azure_sap_automated_deployment/workspaces/sap_system/np-scus-sap0-X00; cd $_ 
- vi np-scus-sap0-X00.json 
```
{ 

  "infrastructure": { 

    "landscape": "np", 

    "region": "southcentralus", 

    "resource_group": { 

      "name": " np-scus-sap0-X00" 

    }, 

    "vnets": { 

      "sap": { 

        "is_existing": "true", 

        "arm_id": "/subscriptions/49dcf07f-3ea3-40f9-a87a-c75a49c32c5f/resourceGroups/np-scus-sap0-infrastructure/providers/Microsoft.Network/virtualNetworks/np-scus-sa[0-vnet", 

        "subnet_admin": { 

          "name": " np-scus-sap0-x00 _admin-subnet", 

          "prefix": "10.1.1.0/24" 

        }, 

        "subnet_db": { 

          "name": " np-scus-sap0-x00_db-subnet", 

          "prefix": "10.1.2.0/24" 

        }, 

        "subnet_app": { 

          "name": "np-scus-sap0-x00_app-subnet", 

          "prefix": "10.1.3.0/24" 

        } 

      } 

    } 

  }, 

  "jumpboxes": { 

    "windows": [], 

    "linux": [] 

  }, 

  "databases": [ 

    { 

      "platform"                : "HANA", 

      "high_availability"       : false, 

      "db_version"              : "2.00.050", 

      "size"                    : "Demo", 

      "os"                      : { 

        "publisher"             : "SUSE", 

        "offer"                 : "sles-sap-12-sp5", 

        "sku"                   : "gen1" 

      }, 

      "instance"                : { 

        "sid"                   : "HDB", 

        "instance_number"       : "00" 

      }, 

      "credentials"             : { 

        "db_systemdb_password"  : "Tr0uble", 

        "os_sidadm_password"    : "Tr0uble", 

        "os_sapadm_password"    : "Tr0uble", 

        "xsa_admin_password"    : "Tr0uble", 

        "cockpit_admin_password": "Tr0uble", 

        "ha_cluster_password"   : "Tr0uble" 

      } 

    } 

  ], 

  "application": { 

    "enable_deployment": false, 

    "sid": "X00", 

    "scs_instance_number": "00", 

    "ers_instance_number": "10", 

    "scs_high_availability": false, 

    "application_server_count": 3, 

    "webdispatcher_count": 1, 

    "authentication" : { 

      "type": "key", 

      "username": "azureadm" 

    } 

  }, 

  "software": { 

    "downloader": { 

      "credentials": { 

        "sap_user": "<sap_user>", 

        "sap_password": "<sap_password>" 

      }, 

      "scenarios": [ 

        { 

          "scenario_type": "DB", 

          "product_name": "HANA", 

          "product_version": "2.0" 

        } 

      ] 

    } 

  }, 

  "sshkey": { 

    "path_to_public_key": "sshkey.pub", 

    "path_to_private_key": "sshkey" 

  }, 
  "options": { 

    "enable_secure_transfer": true, 

    "ansible_execution": false, 

    "enable_prometheus": true 

  } 
} 
```

- cp ~/azure_sap_automated_deployment/workspaces/local/np-scus-deployer-infrastructure/sshkey* . 

- Fetch resource group name, storage account name, container name, there are several ways to do this, eg: 
egrep -wi 'resource_group_name|storage_account_name|container_name' ../../local/np-scus-deployer-infrastructure/.terraform/terraform.tfstate 

Under path ~/azure_sap_automated_deployment/workspaces/sap_system/np-scus-sap0-X00, run the following commands: 
- terraform init                                                                      \ 
               --backend-config "resource_group_name=np-scus-sap_library"     \ 
               --backend-config "storage_account_name=tfstate187c37f9"              \ 
               --backend-config "container_name=saplibrary"                         \ 
               --backend-config "key=np-scus-sap0-X00.terraform.tfstate"      \ 
               ../../../sap-hana/deploy/terraform/run/sap_system/terraform plan 
- terraform plan                                                                      \ 
                --var-file=np-scus-sap0-X00.json                              \ 
                ../../../sap-hana/deploy/terraform/run/sap_system/ 
- terraform apply --auto-approve                                                      \ 
                --var-file=np-scus-sap0-X00.json                              \ 
                ../../../sap-hana/deploy/terraform/run/sap_system/

**Notes:**
Uploading/downloading input json is not within scope 1 

### FAQ
1. What is the relationship between a customer, deployer UAI, saplibrary, sap landscape, sap systems? Is it 1:1, n:1, 1: n or n:m? 
Customer-deployer: 1:n 
Deployer-saplibrary: n:m 
Deployer-saplandscape: 1: n 
Saplandscape-sapsystem: 1:n 
deployer: UAI: 1:1
 
2. What does {Environment} act? Can users use PROD deployer to provision Non-prod sap systems?
{DEPLOYER_VNET} is a logical identifier allowing for support of multiple instances within the same {ENVIRONMENT} and {REGION}. 

The function and permutability is exactly the same as {SAP_VNET}. 

It is entirely possible to never have more than a single instance, and it is also possible to have: 

one per {ENVIRONMENT} 	 

one per {REGION} 	 

one per {ENVIRONMENT} and {REGION} 	 

parallel {ENVIRONMENT} 	 

parallel {REGION} 	 

parallel {ENVIRONMENT} and {REGION}  

you have to think multi-dimensionally. Here is a story. 

A company starts using SAP. It may be their first time. They a using a single region. They set up a sandbox environment with a deployer SND-EUS2-DEPLOY-INFRASTRUCTURE and SAP workload vnet SND-EUS2-SAP0-INFRASTRUCTURE... life it good. 

They are ready to set up their DEV environment so the deploy a DEV SAP workload VNET NP-EUS2-SAP0-INFRASTRUCTURE and it is peered to the Sandbox Deployer SND-EUS2-DEPLOY-INFRASTRUCTURE... They quickly realize this allows for no deployment segregation of duties or blast zone containment, since a breach or misuse in Sandbox would effect both environments. In thinking things through, it is not really DEV they are going to contain, but the Non-Prod (DEV, TST, SPT) side of the house, so they deploy an NP Environment Deployer NP-EUS2-DEPLOY-INFRASTRUCTURE. Now they are faced with a choice they can either move the state for the Non-Prod SAP Workload VNET NP-EUS2-SAP0-INFRASTRUCTURE over to the new Non-Prod deployer NP-EUS2-DEPLOY-INFRASTRUCTURE, change a parameter so it will tear down and peer to the correct deployer, or they could destroy the Non-Prod SAP workload VNET NP-EUS2-SAP0-INFRASTRUCTURE and redeploy it correctly. Life is good. 

They are going to Production usage now and go through the same actions of creating a Prod Deployer and SAP workload VNET. so now their environment looks like this. 

SND-EUS2-DEPLOY-INFRASTRUCTURE <--> SND-EUS2-SAP0-INFRASTRUCTURE 	 

NP-EUS2-DEPLOY-INFRASTRUCTURE <--> NP-EUS2-SAP0-INFRASTRUCTURE 	 

PRD-EUS2-DEPLOY-INFRASTRUCTURE <--> PRD-EUS2-SAP0-INFRASTRUCTURE  

Life goes on... Now they need to Disaster Recovery so they need an VNET in a different region so they create PRD-WUS2-SAP0-INFRASTRUCTURE and it is peered back to the Prod Deployer PRD-EUS2-DEPLOY-INFRASTRUCTURE. One deployer is not controlling multiple workload VNETS in the Prod Environment. Life is good. 

Life continues, the company has grown, and they acquire a new company through an acquisition. Some governance issues surface and they realize that there are data sovereignty issues, so the systems must be partitioned from existing infrastructure. They create a new set is infrastructure, much like what was described above, and this is the outcome: 

SND-EUS2-DEPLOY-INFRASTRUCTURE  <--> SND-EUS2-SAP0-INFRASTRUCTURE  

NP-EUS2-DEPLOY-INFRASTRUCTURE  <-->  NP-EUS2-SAP0-INFRASTRUCTURE 

PRD-EUS2-DEPLOY-INFRASTRUCTURE  <--> PRD-EUS2-SAP0-INFRASTRUCTURE
                                                                +--> PRD-WUS2-SAP0-INFRASTRUCTURE 

SND-EUS2-DEPLOY1-INFRASTRUCTURE <--> SND-EUS2-SAP1-INFRASTRUCTURE  

NP-EUS2-DEPLOY1-INFRASTRUCTURE <-->  NP-EUS2-SAP1-INFRASTRUCTURE 

PRD-EUS2-DEPLOY1-INFRASTRUCTURE <--> PRD-EUS2-SAP1-INFRASTRUCTURE 
                                                                 +--> PRD-WUS2-SAP1-INFRASTRUCTURE  

You may notice that we did not use DEPLOY0 for consistency... we should, but oversights do happen, that would just be an example. Multi dimensional deployers would be rare, but in lab environments with multiple people sharing the same subscription, it would become common. 
Anyway as you can see the naming convention supports parallelism and multi-dimensional configurations, or we could say multiple instances. 

It is also quite possible that the different Environments will have different subscriptions and credentials, which is another segregation of duties scenario and Blast radius containment... You would not want a Sandbox Deployer to effect an outcome on a prod system.

**Comment by rukawata** [comment]
Completed.

**Comment by mkdeegan** [comment]
# Step 1 Feedback

## Workflow

```
mkdir -p ~/azure_sap_automated_deployment/WORKSPACES/LOCAL/NP-SCUS-DEPLOYER-INFRATRUCTURE; cd $_
git clone https://github.com/Azure/sap-hana.git
cd sap-hana; git checkout kimforss-sapsystem-naming
mkdir -p ~/azure_sap_automated_deployment/WORKSPACES/LOCAL/NP-SCUS-DEPLOYER-INFRASTRUCTURE; cd $_
ssh-keygen -q -t rsa -C "Deploy Platform" -f sshkey
vi NP-SCUS-DEPLOYER-INFRASTRUCTURE.json

terraform init ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/

terraform plan --var-file=NP-SCUS-DEPLOYER-INFRASTRUCTURE.json ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/

terraform apply --auto-approve --var-file=NP-SCUS-DEPLOYER-INFRASTRUCTURE.json  ../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/

./post_deployment.sh
```

## NP-SCUS-DEPLOYER-INFRASTRUCTURE.json
```
{
  "infrastructure": {
    "region": "southcentralus",
    "landscape": "np",
    "vnets": {
      "management": {
        "address_space": "10.0.0.0/26",
        "subnet_mgmt": {
          "prefix": "10.0.0.16/28"
        }
      }
    }
  },
  "sshkey": {
    "path_to_public_key": "sshkey.pub",
    "path_to_private_key": "sshkey"
  },
  "options": {
    "enable_secure_transfer": true
  }
}
```

## Observations

- Case was not observed in paths results in pathing problems.
- Landscape used instead of environment. Landscape has a specific meaning in SAP and this can cause confusion.
- Why are all outputs sensitive. Only Passwords and Keys should be sensitive.
- Please consider the workaround structure for the post_deployment.sh it makes it easier to maintain.
- [backlog, maybe] We can create a tokenized wrapper

```
Example: tfplan NP-SCUS-DEPLOYER-INFRASTRUCTURE

tfplan:
#!/bin/bash

workspace=$1
tfModulePath=”../../../sap-hana/deploy/terraform/bootstrap/sap_deployer/”

terraform plan --var-file=${workspace}.json --state=${workspace} ${tfModulePath}
```

## Workaround
post_deployment.sh
```
local_file_dir=$(dirname "$BASH_SOURCE")
workspace="NP-SCUS-DEPLOYER-INFRASTRUCTURE"
remote_dir="~/azure_sap_automated_deployment/WORKSPACES/LOCAL/${workspace}"

ssh -i sshkey  -o StrictHostKeyChecking=no azureadm@13.85.75.171 "mkdir -p ${remote_dir}"

printf "%s\n" "Start uploading ${workspace} tfstate"
scp -i sshkey -o StrictHostKeyChecking=no ${local_file_dir}/../${}.terraform.tfstate azureadm@13.85.75.171:${remote_dir}

printf "%s\n" "Start uploading ${workspace} json"
scp -i sshkey -o StrictHostKeyChecking=no ${local_file_dir}/../${workspace}.json azureadm@13.85.75.171:${remote_dir}

printf "%s\n" "Start uploading SSH Keys"
scp -i sshkey -o StrictHostKeyChecking=no ${local_file_dir}/../sshkey* azureadm@13.85.75.171:${remote_dir}
```

## Results
Issues present

**Comment by rukawata** [comment]
> Observations
> 
> - Case was not observed in paths results in pathing problems.

Sorry, not very clear. What is this referring to?
> - Landscape used instead of environment. Landscape has a specific meaning in SAP and this can cause confusion.

Naming of input, not functional side. keep as backlog and potentially can be done as part of tfvar changes.

> - Why are all outputs sensitive. Only Passwords and Keys should be sensitive.

Because we do not want those log show up in pipeline testing.
We can selectively mask information when we work on cleaning up output information.
Backlog item.

> - Please consider the workaround structure for the post_deployment.sh it makes it easier to maintain.

Good suggestion. Will fix now.

> - [backlog, maybe] We can create a tokenized wrapper

Agreed.
