### ISSUE TITLE
[BUG] HA deployment fails at "sap_hana_fencing_agent_subscription_id" assertion

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#734]
**Describe the bug**
When following https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md and running deployment based on the provided template, the deployment fails at the following stage:

null_resource.ansible_playbook[0] (remote-exec): TASK [hana-os-clustering : Check the fencing agent configuration variables are set] ***
null_resource.ansible_playbook[0] (remote-exec): fatal: [10.101.1.10]: FAILED! => {
null_resource.ansible_playbook[0] (remote-exec):     "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
null_resource.ansible_playbook[0] (remote-exec):     "changed": false,
null_resource.ansible_playbook[0] (remote-exec):     "evaluated_to": false,
null_resource.ansible_playbook[0] (remote-exec):     "msg": "Assertion failed"
null_resource.ansible_playbook[0] (remote-exec): }
null_resource.ansible_playbook[0] (remote-exec): fatal: [10.101.1.11]: FAILED! => {
null_resource.ansible_playbook[0] (remote-exec):     "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
null_resource.ansible_playbook[0] (remote-exec):     "changed": false,
null_resource.ansible_playbook[0] (remote-exec):     "evaluated_to": false,
null_resource.ansible_playbook[0] (remote-exec):     "msg": "Assertion failed"
null_resource.ansible_playbook[0] (remote-exec): }

null_resource.ansible_playbook[0] (remote-exec): NO MORE HOSTS LEFT *****************

**To reproduce**
1. Set up deployment environment (e.g. Azure Cloud Shell) by following the **Obtaining the Code** section of https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md
2. Copy the included template (template-ha1.json) to /deploy/template_samples
3. Run the following 

source util/source_path.sh
az account set --subscription "subscription_ID"
check_subscription.sh
create_service_principal.sh sp-hanav2xxxxxxxxxxx
set_sap_download_credentials.sh username password
set_resource_group.sh hanav2-ha-RG template-ha1
set_ha_cluster_password.sh ASecurePa55w0rd template-ha1
create_fencing_agent.sh HN1
terraform_v2.sh init
terraform_v2.sh plan template-ha1
terraform_v2.sh apply template-ha1

null_resource.ansible_playbook[0] (remote-exec): TASK [hana-os-clustering : Check the fencing agent configuration variables are set] ***
null_resource.ansible_playbook[0] (remote-exec): fatal: [10.101.1.10]: FAILED! => {
null_resource.ansible_playbook[0] (remote-exec):     "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
null_resource.ansible_playbook[0] (remote-exec):     "changed": false,
null_resource.ansible_playbook[0] (remote-exec):     "evaluated_to": false,
null_resource.ansible_playbook[0] (remote-exec):     "msg": "Assertion failed"
null_resource.ansible_playbook[0] (remote-exec): }
null_resource.ansible_playbook[0] (remote-exec): fatal: [10.101.1.11]: FAILED! => {
null_resource.ansible_playbook[0] (remote-exec):     "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
null_resource.ansible_playbook[0] (remote-exec):     "changed": false,
null_resource.ansible_playbook[0] (remote-exec):     "evaluated_to": false,
null_resource.ansible_playbook[0] (remote-exec):     "msg": "Assertion failed"
null_resource.ansible_playbook[0] (remote-exec): }

null_resource.ansible_playbook[0] (remote-exec): NO MORE HOSTS LEFT *****************

null_resource.ansible_playbook[0] (remote-exec): PLAY RECAP *********************************************************************
null_resource.ansible_playbook[0] (remote-exec): 10.101.1.10                : ok=93   changed=36   unreachable=0    failed=1    skipped=48   rescued=0    ignored=0
null_resource.ansible_playbook[0] (remote-exec): 10.101.1.11                : ok=85   changed=39   unreachable=0    failed=1    skipped=53   rescued=0    ignored=0
null_resource.ansible_playbook[0] (remote-exec): 10.101.4.4                 : ok=11   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
null_resource.ansible_playbook[0] (remote-exec): 10.101.4.5                 : ok=11   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
null_resource.ansible_playbook[0] (remote-exec): 10.101.4.6                 : ok=11   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
null_resource.ansible_playbook[0] (remote-exec): localhost                  : ok=18   changed=10   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Error: error executing "/tmp/terraform_815849359.sh": Process exited with status 2

**Expected behavior**
Deployment completing successfully.

**Additional context**

I verified that default/export-clustering-sp-details.sh exists and contains subscription_ID (obfuscated in the following listing)

cat default/export-clustering-sp-details.sh
export SAP_HANA_FENCING_AGENT_SUBSCRIPTION_ID=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
export SAP_HANA_FENCING_AGENT_TENANT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
export SAP_HANA_FENCING_AGENT_CLIENT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
export SAP_HANA_FENCING_AGENT_CLIENT_SECRET="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

here is the template:
{
  "infrastructure": {
    "region": "eastus",
    "resource_group": {
      "is_existing": "false",
      "name": "hanav2-ha-RG"
    },
    "ppg": {
      "is_existing": "false",
      "name": "hanav2-ha-ppg"
    },
    "vnets": {
      "management": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-mgmt",
        "address_space": "10.100.0.0/16",
        "subnet_mgmt": {
          "is_existing": "false",
          "name": "subnet-mgmt",
          "prefix": "10.100.0.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-mgmt",
            "allowed_ips": [
              "0.0.0.0/0"
            ]
          }
        }
      },
      "sap": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-sap",
        "address_space": "10.101.0.0/16",
        "subnet_admin": {
          "is_existing": "false",
          "name": "subnet-admin",
          "prefix": "10.101.1.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-admin"
          }
        },
        "subnet_db": {
          "is_existing": "false",
          "name": "subnet-db",
          "prefix": "10.101.2.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-db"
          }
        },
        "subnet_app": {
          "is_existing": "false",
          "name": "subnet-app",
          "prefix": "10.101.3.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-app"
          }
        },
        "subnet_iscsi": {
          "is_existing": "false",
          "name": "subnet-iscsi",
          "prefix": "10.101.4.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-iscsi"
          }
        }
      }
    },
    "iscsi": {
      "iscsi_count": 3,
      "size":"Standard_D2s_v3",
      "os": {
        "publisher": "SUSE",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1",
        "version": "latest"
      },
      "authentication": {
        "type": "key",
        "username": "azureadm"
      }
    }
  },
  "jumpboxes": {
    "windows": [
      {
        "name": "hanav2jmp-vm0",
        "destroy_after_deploy": "false",
        "size": "Standard_D2s_v3",
        "disk_type": "StandardSSD_LRS",
        "os": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter"
        },
        "authentication": {
          "type": "password",
          "username": "azureadm",
          "password": "Sap@hana2019!"
        },
        "components": []
      }
    ],
    "linux": []
  },
  "databases": [
    {
      "platform": "HANA",
      "db_version": "2.00.043",
      "os": {
        "publisher": "suse",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1"
      },
      "size": "Demo",
      "filesystem": "xfs",
      "high_availability": true,
      "authentication": {
        "type": "key",
        "username": "azureadm"
      },
      "instance": {
        "sid": "HN1",
        "instance_number": "00"
      },
      "credentials": {
        "db_systemdb_password": "Manager1",
        "os_sidadm_password": "Help4you",
        "os_sapadm_password": "Help4you",
        "xsa_admin_password": "Manager1",
        "cockpit_admin_password": "Manager1",
        "ha_cluster_password": "ASecurePa55w0rd"
      },
      "dbnodes": [
        {
          "name": "hdb1",
          "role": "worker"
        }
      ],
      "components": {
        "hana_database": [],
        "hana_client_linux": []
      },
      "xsa": {
        "routing": "ports"
      },
      "shine": {
        "email": "shinedemo@microsoft.com"
      },
      "loadbalancer": {}
    }
  ],
  "application": {
    "sid": "HN1",
    "enable_deployment": false,
    "scs_instance_number": "01",
    "ers_instance_number": "02",
    "scs_high_availability": false,
    "application_server_count": 1,
    "webdispatcher_count": 1,
    "vm_sizing": "Default",
    "authentication": {
      "type": "key",
      "username": "azureadm"
    },
    "os": {
      "publisher": "suse",
      "offer": "sles-sap-12-sp5",
      "sku": "gen1"
    }
  },
  "software": {
    "storage_account_sapbits": {
      "is_existing": false,
      "account_tier": "Premium",
      "account_replication_type": "LRS",
      "account_kind": "FileStorage",
      "file_share_name": "bits",
      "container_access_type": "private",
      "storage_account_name": "sapbitsaccount083020"
    },
    "downloader": {
      "credentials": {
        "sap_user": "",
        "sap_password": ""
      },
      "scenarios": [
        {
          "scenario_type": "DB",
          "product_name": "HANA",
          "product_version": "2.0",
          "os_type": "LINUX_X64",
          "os_version": "SLES12.3",
          "components": [
            "PLATFORM"
          ]
        },
        {
          "scenario_type": "RTI",
          "product_name": "RTI",
          "os_type": "LINUX_X64"
        },
        {
          "scenario_type": "BASTION",
          "os_type": "NT_X64"
        }
      ],
      "debug": {
        "enabled": false,
        "cert": "charles.pem",
        "proxies": {
          "http": "http://127.0.0.1:8888",
          "https": "https://127.0.0.1:8888"
        }
      }
    }
  },
  "sshkey": {
    "path_to_public_key": "~/.ssh/id_rsa.pub",
    "path_to_private_key": "~/.ssh/id_rsa"
  },
  "options": {
    "enable_secure_transfer": true,
    "ansible_execution": true,
    "enable_prometheus": false
  }
}

pls advise
rgds
Marcin

**Comment by rukawata** [comment]
Hi @polichtm ,

Can you check file `export-clustering-sp-details.sh` on the VM rti?
If it is not empty, then maybe you need to run `source export-clustering-sp-details.sh` before the ansible-playbook.

This script is generated to setup SP for azure fencing agent.

Thanks,
Nancy

**Comment by polichtm** [comment]
Hi @rukawata 
interestingly the process completes successfully if I run the Ansible part from RTI. That's actually good enough for me. Appreciate the prompt response.
rgds
Marcin
