### ISSUE TITLE
[BUG] Duplicate STONITH configuration

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#739]
**Describe the bug**
When following https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md and running deployment based on the template provided below, the deployment results in two STONITH resources.

**To reproduce**

Set up deployment environment (e.g. Azure Cloud Shell) by following the Obtaining the Code section of https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md
Copy the included template (template-ha1.json) to /deploy/template_samples
Run the following
source util/source_path.sh
az account set --subscription "subscription_ID"
check_subscription.sh
create_service_principal.sh sp-hanav2xxxxxxxxxxx
set_sap_download_credentials.sh username password
set_resource_group.sh hanav2-ha-RG template-ha1
set_ha_cluster_password.sh ASecurePa55w0rd template-ha1
create_fencing_agent.sh HN1
terraform_v2.sh init
terraform_v2.sh plan template-ha1
terraform_v2.sh apply template-ha1

**Expected behavior**
A cluster should have only a single STONITH resource (either SDB or Azure fencing agent)

**Additional context**
Here is a screenshot of HAWK interface illustrating the issue:
![image](https://user-images.githubusercontent.com/10284906/91778555-d8193400-ebc0-11ea-83be-98d72cb54338.png)

here is the template:

{
  "infrastructure": {
    "region": "eastus",
    "resource_group": {
      "is_existing": "false",
      "name": "hanav2-ha-RG"
    },
    "ppg": {
      "is_existing": "false",
      "name": "hanav2-ha-ppg"
    },
    "vnets": {
      "management": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-mgmt",
        "address_space": "10.100.0.0/16",
        "subnet_mgmt": {
          "is_existing": "false",
          "name": "subnet-mgmt",
          "prefix": "10.100.0.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-mgmt",
            "allowed_ips": [
              "0.0.0.0/0"
            ]
          }
        }
      },
      "sap": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-sap",
        "address_space": "10.101.0.0/16",
        "subnet_admin": {
          "is_existing": "false",
          "name": "subnet-admin",
          "prefix": "10.101.1.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-admin"
          }
        },
        "subnet_db": {
          "is_existing": "false",
          "name": "subnet-db",
          "prefix": "10.101.2.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-db"
          }
        },
        "subnet_app": {
          "is_existing": "false",
          "name": "subnet-app",
          "prefix": "10.101.3.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-app"
          }
        },
        "subnet_iscsi": {
          "is_existing": "false",
          "name": "subnet-iscsi",
          "prefix": "10.101.4.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-iscsi"
          }
        }
      }
    },
    "iscsi": {
      "iscsi_count": 3,
      "size":"Standard_D2s_v3",
      "os": {
        "publisher": "SUSE",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1",
        "version": "latest"
      },
      "authentication": {
        "type": "key",
        "username": "azureadm"
      }
    }
  },
  "jumpboxes": {
    "windows": [
      {
        "name": "hanav2jmp-vm0",
        "destroy_after_deploy": "false",
        "size": "Standard_D2s_v3",
        "disk_type": "StandardSSD_LRS",
        "os": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter"
        },
        "authentication": {
          "type": "password",
          "username": "azureadm",
          "password": "Sap@hana2019!"
        },
        "components": []
      }
    ],
    "linux": []
  },
  "databases": [
    {
      "platform": "HANA",
      "db_version": "2.00.043",
      "os": {
        "publisher": "suse",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1"
      },
      "size": "Demo",
      "filesystem": "xfs",
      "high_availability": true,
      "authentication": {
        "type": "key",
        "username": "azureadm"
      },
      "instance": {
        "sid": "HN1",
        "instance_number": "00"
      },
      "credentials": {
        "db_systemdb_password": "Manager1",
        "os_sidadm_password": "Help4you",
        "os_sapadm_password": "Help4you",
        "xsa_admin_password": "Manager1",
        "cockpit_admin_password": "Manager1",
        "ha_cluster_password": "ASecurePa55w0rd"
      },
      "dbnodes": [
        {
          "name": "hdb1",
          "role": "worker"
        }
      ],
      "components": {
        "hana_database": [],
        "hana_client_linux": []
      },
      "xsa": {
        "routing": "ports"
      },
      "shine": {
        "email": "shinedemo@microsoft.com"
      },
      "loadbalancer": {}
    }
  ],
  "application": {
    "sid": "HN1",
    "enable_deployment": false,
    "scs_instance_number": "01",
    "ers_instance_number": "02",
    "scs_high_availability": false,
    "application_server_count": 1,
    "webdispatcher_count": 1,
    "vm_sizing": "Default",
    "authentication": {
      "type": "key",
      "username": "azureadm"
    },
    "os": {
      "publisher": "suse",
      "offer": "sles-sap-12-sp5",
      "sku": "gen1"
    }
  },
  "software": {
    "storage_account_sapbits": {
      "is_existing": false,
      "account_tier": "Standard",
      "account_replication_type": "LRS",
      "account_kind": "Storage",
      "blob_container_name": "bits",
      "container_access_type": "private",
      "storage_account_name": "sapbitsha083020ha"
    },
    "downloader": {
      "credentials": {
        "sap_user": "",
        "sap_password": ""
      },
      "scenarios": [
        {
          "scenario_type": "DB",
          "product_name": "HANA",
          "product_version": "2.0",
          "os_type": "LINUX_X64",
          "os_version": "SLES12.3",
          "components": [
            "PLATFORM"
          ]
        },
        {
          "scenario_type": "RTI",
          "product_name": "RTI",
          "os_type": "LINUX_X64"
        },
        {
          "scenario_type": "BASTION",
          "os_type": "NT_X64"
        }
      ],
      "debug": {
        "enabled": false,
        "cert": "charles.pem",
        "proxies": {
          "http": "http://127.0.0.1:8888",
          "https": "https://127.0.0.1:8888"
        }
      }
    }
  },
  "sshkey": {
    "path_to_public_key": "~/.ssh/id_rsa.pub",
    "path_to_private_key": "~/.ssh/id_rsa"
  },
  "options": {
    "enable_secure_transfer": true,
    "ansible_execution": false,
    "enable_prometheus": false
  }
}

rgds
Marcin

**Comment by rukawata** [comment]
Hi Marcin @polichtm ,

We created per Microsoft [doc](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability#create-sap-hana-cluster-resources), which creates both SBD and azure fencing agent.

Actually I notice that `rsc_st_azure` which is the fencing agent is not start up properly. I would be interested to see what is the problem. One known issue I've experienced was with `SLES12 SP05`, azure python sdk is missing on the image (SUSE switched over to python3 to support azure-cli). To workaround that, one would need to manually install `python-azure-mgmt-compute` package. Afterwards the azure fencing agent can start without any problem.

Hope it helps.

Thanks,
Nancy

**Comment by polichtm** [comment]
Hi Nancy @rukawata 

why would a cluster need two STONITH resources?

As far as I understand, https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker states that's either/or configuration - not both. 

"There are two options to set up a Pacemaker cluster in Azure. You can **_either_** use a fencing agent, which takes care of restarting a failed node via the Azure APIs **_or_** you can use an SBD device."

"The configuration in this section is only applicable, if using SBD STONITH.
    [1] Enable the use of a STONITH device and set the fence delay"

"This section of the documentation is only applicable, if using STONITH, based on Azure Fence agent."

rgds
Marcin

**Comment by polichtm** [comment]
Hi Nancy @rukawata 
Btw. I installed the package python-azure-mgmt-compute package on both nodes (by following https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker) but the fencing agent still fails to start 
rgds
Marcin

**Comment by rukawata** [comment]
Hi Marcin @polichtm ,
I see your reference is a general document for SUSE HA whereas my reference was HANA HA specific.
I will double check with the owner of the topic on how we should handle this, then get back to you.
Before that, if you need to remove azure fencing agent, you can run below command:
```
sudo crm resource list
sudo crm resource stop <resource name, eg. rsc_st_azure>
sudo crm configure delete <resource name, eg. rsc_st_azure>
```

As for the azure fencing agent not able to start, we will try to reproduce the issue. If we can't, you may have to report to SUSE to continue the investigation.

Thanks!
Nancy

**Comment by rukawata** [comment]
Hi Marcin @polichtm,
We've checked with owner and now the HANA HA [doc](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability#create-sap-hana-cluster-resources) has been update to not have azure fencing agent while SBD used.

We are working on getting this change into the code base.

Thanks!
Nancy

**Comment by polichtm** [comment]
Hi Nancy @rukawata 
greatly appreciated
rgds
Marcin
