### ISSUE TITLE
[BUG] Deployer VNET Naming

### ISSUE THREAD

**Issue by mkdeegan** [Azure/sap-hana#750]
**Describe the bug**
A default value is assumed for the `DEPLOY_VNET` of `DEPLOYER`, it it is not provided.
If a value is provided for the `DEPLOY_VNET` then the VNET is not created following the Naming Standard.
As the value of `DEPLOY_VNET` is part of the Naming Convention, It should be a required input with no default value.

**Comment by KimForss** [comment]
and in cases where the customer wants to deploy multiple deployers into the same DEPLOY-VNET they use the arm_id (in future state references)

So the expected result when DEPLOY_VNET is not provided is a deployment failure?

**Comment by mkdeegan** [comment]
Multiple deployed in the same DEPLOY_VNET a function of incrementing the number of deployers, much like app servers... but we have not enabled that use case yet

**Comment by KimForss** [comment]
And with the arm_id (future state file) we can also support the use case for having deployers for multiple different environments (Test / QA) in the same DEPLOY_VNET
 
With my current code the expected result when DEPLOY_VNET is not provided is a deployment failure, is that correct

**Comment by mkdeegan** [comment]
Multiple deployers in the same DEPLOY_VNET should be a function of an increased count type functionality in the already deployed Deployer. But we can think about what makes the most sense and this has not been an enabled scenario yet...
It is a good way to think forward, thought, as it will be a use case.

**Comment by mkdeegan** [comment]
`With my current code the expected result when DEPLOY_VNET is not provided is a deployment failure, is that correct`
yes

**Comment by mkdeegan** [comment]
sorry for the repetition... I initially did not see that my email response from my phone made it in.

**Comment by KimForss** [comment]
np - I guessed that was the case :)

**Comment by KimForss** [comment]
With this json

![image](https://user-images.githubusercontent.com/25486924/92331670-f085c480-f080-11ea-932b-1b63bfabf349.png)

the result is

![image](https://user-images.githubusercontent.com/25486924/92331626-d51ab980-f080-11ea-9b8c-65807151aaa7.png)

PR : https://github.com/Azure/sap-hana/pull/754
