### ISSUE TITLE
[BUG] Naming Convention Error

### ISSUE THREAD

**Issue by mkdeegan** [Azure/sap-hana#753]
**Describe the bug**
There is a naming convention error in the **v1.0-beta** branch.
The subnet name and NSG names for **web** and **app** are a partial duplication of prefix.

```
NP-EUS2-NP-EUS2-X00_web-subnet NP-EUS2-NP-EUS2-X00_webSubnet-nsg
NP-EUS2-SAP0-X00_admin-subnet  NP-EUS2-SAP0-X00_adminSubnet-nsg
NP-EUS2-SAP0-X00_db-subnet     NP-EUS2-SAP0-X00_dbSubnet-nsg
NP-EUS2-NP-EUS2-X00_app-subnet NP-EUS2-NP-EUS2-X00_appSubnet-nsg
NP-EUS2-NP-EUS2-X01_app-subnet NP-EUS2-NP-EUS2-X01_appSubnet-nsg
NP-EUS2-SAP0-X01_admin-subnet  NP-EUS2-SAP0-X01_adminSubnet-nsg
NP-EUS2-SAP0-X01_db-subnet     NP-EUS2-SAP0-X01_dbSubnet-nsg
NP-EUS2-NP-EUS2-X01_web-subnet NP-EUS2-NP-EUS2-X01_webSubnet-nsg
NP-EUS2-SAP0-X02_admin-subnet  NP-EUS2-SAP0-X02_adminSubnet-nsg
NP-EUS2-SAP0-X02_db-subnet.    NP-EUS2-SAP0-X02_dbSubnet-nsg
NP-EUS2-NP-EUS2-X02_app-subnet NP-EUS2-NP-EUS2-X02_appSubnet-nsg
NP-EUS2-NP-EUS2-X02_web-subnet NP-EUS2-NP-EUS2-X02_webSubnet-nsg
```

**Comment by mkdeegan** [comment]
This is also occurring with NIC and Load Balancer

**Comment by mkdeegan** [comment]
![Screen Shot 2020-09-06 at 9 04 01 AM](https://user-images.githubusercontent.com/54906896/92329956-ff885a80-f01f-11ea-932a-72ef9811c864.png)
![Screen Shot 2020-09-06 at 9 05 18 AM](https://user-images.githubusercontent.com/54906896/92329966-1c249280-f020-11ea-8543-121f5356b547.png)

**Comment by KimForss** [comment]
Regression introduced when working on scaleout node naming, code fixed

PR https://github.com/Azure/sap-hana/pull/755 created
