### ISSUE TITLE
[BUG] Setup SBD should not depend on fencing agent info

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#809]
Describe the bug
It appears that HA deployment relies on the presence of the fencing agent configuration even when using SDB-based STONITH (i.e it is necessary to run create_fencing_agent.sh to create the fencing agent service principal and assign to it the Contributor role on the subscription level even when not using it).

When following https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md and running deployment based on the template provided below, the deployment fails with the following message:
TASK [hana-system-replication : Determine if HANA is running] ************************************************************
skipping: [10.101.1.10]
skipping: [10.101.1.11]

TASK [hana-system-replication : Ensure HANA is running] ******************************************************************
skipping: [10.101.1.10]
skipping: [10.101.1.11]

TASK [hana-system-replication : Check HANA is running] *******************************************************************
skipping: [10.101.1.10]
skipping: [10.101.1.11]

TASK [hana-system-replication : Ensure replication status is active] *****************************************************
skipping: [10.101.1.11]
ok: [10.101.1.10]

TASK [hana-os-clustering : Check the fencing agent configuration variables are set] **************************************
fatal: [10.101.1.10]: FAILED! => {
    "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
fatal: [10.101.1.11]: FAILED! => {
    "assertion": "sap_hana_fencing_agent_subscription_id | trim | length > 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

NO MORE HOSTS LEFT *******************************************************************************************************

PLAY RECAP ***************************************************************************************************************
10.101.1.10                : ok=67   changed=9    unreachable=0    failed=1    skipped=69   rescued=0    ignored=0
10.101.1.11                : ok=51   changed=9    unreachable=0    failed=1    skipped=82   rescued=0    ignored=0
10.101.4.4                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.101.4.5                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.101.4.6                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=13   changed=1    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0

To reproduce

Set up deployment environment (e.g. Azure Cloud Shell) by following the Obtaining the Code section of https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md
Copy the included template (template-ha1.json) to /deploy/template_samples
Run the following
source util/source_path.sh
az account set --subscription "subscription_ID"
check_subscription.sh
create_service_principal.sh sp-hanav2xxxxxxxxxxx
set_sap_download_credentials.sh username password
set_resource_group.sh hanav2-ha-RG template-ha1
set_ha_cluster_password.sh ASecurePa55w0rd template-ha1

### Do not run create_fencing_agent.sh HN1

terraform_v2.sh init
terraform_v2.sh plan template-ha1
terraform_v2.sh apply template-ha1

Expected behavior
The deployment should use SDB-based STONITH (without dependency on the Azure fencing agent)

Additional context
here is the template:

   {
     "infrastructure": {
       "region": "eastus",
       "resource_group": {
         "is_existing": "false",
         "name": "hanav2-ha-RG"
       },
       "ppg": {
         "is_existing": "false",
         "name": "hanav2-ha-ppg"
       },
       "vnets": {
         "management": {
           "is_existing": "false",
           "name": "hanav2-ha-vnet-mgmt",
           "address_space": "10.100.0.0/16",
           "subnet_mgmt": {
             "is_existing": "false",
             "name": "subnet-mgmt",
             "prefix": "10.100.0.0/24",
             "nsg": {
               "is_existing": "false",
               "name": "nsg-mgmt",
               "allowed_ips": [
                 "0.0.0.0/0"
               ]
             }
           }
         },
         "sap": {
           "is_existing": "false",
           "name": "hanav2-ha-vnet-sap",
           "address_space": "10.101.0.0/16",
           "subnet_admin": {
             "is_existing": "false",
             "name": "subnet-admin",
             "prefix": "10.101.1.0/24",
             "nsg": {
               "is_existing": "false",
               "name": "nsg-admin"
             }
           },
           "subnet_db": {
             "is_existing": "false",
             "name": "subnet-db",
             "prefix": "10.101.2.0/24",
             "nsg": {
               "is_existing": "false",
               "name": "nsg-db"
             }
           },
           "subnet_app": {
             "is_existing": "false",
             "name": "subnet-app",
             "prefix": "10.101.3.0/24",
             "nsg": {
               "is_existing": "false",
               "name": "nsg-app"
             }
           },
           "subnet_iscsi": {
             "is_existing": "false",
             "name": "subnet-iscsi",
             "prefix": "10.101.4.0/24",
             "nsg": {
               "is_existing": "false",
               "name": "nsg-iscsi"
             }
           }
         }
       },
       "iscsi": {
         "iscsi_count": 3,
         "size":"Standard_D2s_v3",
         "os": {
           "publisher": "SUSE",
           "offer": "sles-sap-12-sp5",
           "sku": "gen1",
           "version": "latest"
         },
         "authentication": {
           "type": "key",
           "username": "azureadm"
         }
       }
     },
     "jumpboxes": {
       "windows": [
         {
           "name": "hanav2jmp-vm0",
           "destroy_after_deploy": "false",
           "size": "Standard_D2s_v3",
           "disk_type": "StandardSSD_LRS",
           "os": {
             "publisher": "MicrosoftWindowsServer",
             "offer": "WindowsServer",
             "sku": "2019-Datacenter"
           },
           "authentication": {
             "type": "password",
             "username": "azureadm",
             "password": "Sap@hana2019!"
           },
           "components": []
         }
       ],
       "linux": []
     },
     "databases": [
       {
         "platform": "HANA",
         "db_version": "2.00.043",
         "os": {
           "publisher": "suse",
           "offer": "sles-sap-12-sp5",
           "sku": "gen1"
         },
         "size": "Demo",
         "filesystem": "xfs",
         "high_availability": true,
         "authentication": {
           "type": "key",
           "username": "azureadm"
         },
         "instance": {
           "sid": "HN1",
           "instance_number": "00"
         },
         "credentials": {
           "db_systemdb_password": "Manager1",
           "os_sidadm_password": "Help4you",
           "os_sapadm_password": "Help4you",
           "xsa_admin_password": "Manager1",
           "cockpit_admin_password": "Manager1",
           "ha_cluster_password": "ASecurePa55w0rd"
         },
         "dbnodes": [
           {
             "name": "hdb1",
             "role": "worker"
           }
         ],
         "components": {
           "hana_database": [],
           "hana_client_linux": []
         },
         "xsa": {
           "routing": "ports"
         },
         "shine": {
           "email": "shinedemo@microsoft.com"
         },
         "loadbalancer": {}
       }
     ],
     "application": {
       "sid": "HN1",
       "enable_deployment": true,
       "scs_instance_number": "01",
       "ers_instance_number": "02",
       "scs_high_availability": true,
       "application_server_count": 1,
       "webdispatcher_count": 1,
       "vm_sizing": "Default",
       "authentication": {
         "type": "key",
         "username": "azureadm"
       },
       "os": {
         "os_type": "Linux",
         "publisher": "suse",
         "offer": "sles-sap-12-sp5",
         "sku": "gen1"
       }
     },
     "software": {
       "storage_account_sapbits": {
         "is_existing": false,
         "account_tier": "Standard",
         "account_replication_type": "LRS",
         "account_kind": "Storage",
         "blob_container_name": "bits",
         "container_access_type": "private",
         "storage_account_name": "VAR_STORAGE_ACCOUNT_NAME"
       },
       "downloader": {
         "credentials": {
           "sap_user": "",
           "sap_password": ""
         },
         "scenarios": [
           {
             "scenario_type": "DB",
             "product_name": "HANA",
             "product_version": "2.0",
             "os_type": "LINUX_X64",
             "os_version": "SLES12.3",
             "components": [
               "PLATFORM"
             ]
           },
           {
             "scenario_type": "RTI",
             "product_name": "RTI",
             "os_type": "LINUX_X64"
           },
           {
             "scenario_type": "BASTION",
             "os_type": "NT_X64"
           }
         ],
         "debug": {
           "enabled": false,
           "cert": "charles.pem",
           "proxies": {
             "http": "http://127.0.0.1:8888",
             "https": "https://127.0.0.1:8888"
           }
         }
       }
     },
     "sshkey": {
       "path_to_public_key": "~/.ssh/id_rsa.pub",
       "path_to_private_key": "~/.ssh/id_rsa"
     },
     "options": {
       "enable_secure_transfer": true,
       "ansible_execution": false,
       "enable_prometheus": false
     }
   }

rgds
Marcin

**Comment by rukawata** [comment]
Hi @polichtm Marcin,
This should be fixed now. Please let us know otherwise.

Thanks,
Nancy

**Comment by polichtm** [comment]
Hi @rukawata Nancy,
appreciate super speedy resolution. Will give it a try shortly
rgds
Marcin

**Comment by polichtm** [comment]
Hi @rukawata Nancy,
just verified it - thnx again...

I have a  follow up questions - can you advise how I would go about implementing Azure AD fencing agent only (without SDB-based STONITH)?  What is the required content of the ARM template in such case? Is there anything else that's needed?

In addition, it appears that it is always required to provide SAP ID - even if all required software is already present in the storage account I designate. Is this intentional?

rgds
Marcin
