### ISSUE TITLE
[BUG] Not able to RDP on windows jumpbox

### ISSUE THREAD

**Issue by polichtm** [Azure/sap-hana#818]
**Describe the bug**
I'm seeing the following issue when performing an HA deployment using the template included below.
The Windows jumpbox VM is online - I can connect to it via RDP.
In short, the Ansible-based provisioning fails due to apparent connectivity issue to the Windows jumpbox:

PLAY [jumpboxes_windows] ********************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
fatal: [10.100.0.4]: UNREACHABLE! => {"changed": false, "msg": "ntlm: HTTPSConnectionPool(host='10.100.0.4', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0cf1ace860>, 'Connection to 10.100.0.4 timed out. (connect timeout=30)'))", "unreachable": true}

PLAY RECAP **********************************************************************************************************
10.100.0.4                 : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
10.101.1.10                : ok=80   changed=11   unreachable=0    failed=0    skipped=81   rescued=0    ignored=0
10.101.1.11                : ok=63   changed=11   unreachable=0    failed=0    skipped=94   rescued=0    ignored=0
10.101.4.4                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.101.4.5                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.101.4.6                 : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=13   changed=1    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0

**To reproduce**
1. Run deployment by following https://github.com/Azure/sap-hana/blob/master/deploy/USAGE.md using the template included below

**Expected behavior**
Ansible-based provisioning should complete successfully 

{
  "infrastructure": {
    "region": "eastus",
    "resource_group": {
      "is_existing": "false",
      "name": "hanav2-ha-RG"
    },
    "ppg": {
      "is_existing": "false",
      "name": "hanav2-ha-ppg"
    },
    "vnets": {
      "management": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-mgmt",
        "address_space": "10.100.0.0/16",
        "subnet_mgmt": {
          "is_existing": "false",
          "name": "subnet-mgmt",
          "prefix": "10.100.0.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-mgmt",
            "allowed_ips": [
              "0.0.0.0/0"
            ]
          }
        }
      },
      "sap": {
        "is_existing": "false",
        "name": "hanav2-ha-vnet-sap",
        "address_space": "10.101.0.0/16",
        "subnet_admin": {
          "is_existing": "false",
          "name": "subnet-admin",
          "prefix": "10.101.1.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-admin"
          }
        },
        "subnet_db": {
          "is_existing": "false",
          "name": "subnet-db",
          "prefix": "10.101.2.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-db"
          }
        },
        "subnet_app": {
          "is_existing": "false",
          "name": "subnet-app",
          "prefix": "10.101.3.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-app"
          }
        },
        "subnet_iscsi": {
          "is_existing": "false",
          "name": "subnet-iscsi",
          "prefix": "10.101.4.0/24",
          "nsg": {
            "is_existing": "false",
            "name": "nsg-iscsi"
          }
        }
      }
    },
    "iscsi": {
      "iscsi_count": 3,
      "size":"Standard_D2s_v3",
      "os": {
        "publisher": "SUSE",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1",
        "version": "latest"
      },
      "authentication": {
        "type": "key",
        "username": "azureadm"
      }
    }
  },
  "jumpboxes": {
    "windows": [
      {
        "name": "hanav2jmp-vm0",
        "destroy_after_deploy": "false",
        "size": "Standard_D2s_v3",
        "disk_type": "StandardSSD_LRS",
        "os": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter"
        },
        "authentication": {
          "type": "password",
          "username": "azureadm",
          "password": "Sap@hana2019!"
        },
        "components": []
      }
    ],
    "linux": []
  },
  "databases": [
    {
      "platform": "HANA",
      "db_version": "2.00.043",
      "os": {
        "publisher": "suse",
        "offer": "sles-sap-12-sp5",
        "sku": "gen1"
      },
      "size": "Demo",
      "filesystem": "xfs",
      "high_availability": true,
      "authentication": {
        "type": "key",
        "username": "azureadm"
      },
      "instance": {
        "sid": "HN1",
        "instance_number": "00"
      },
      "credentials": {
        "db_systemdb_password": "Manager1",
        "os_sidadm_password": "Help4you",
        "os_sapadm_password": "Help4you",
        "xsa_admin_password": "Manager1",
        "cockpit_admin_password": "Manager1",
        "ha_cluster_password": "ASecurePa55w0rd"
      },
      "dbnodes": [
        {
          "name": "hdb1",
          "role": "worker"
        }
      ],
      "components": {
        "hana_database": [],
        "hana_client_linux": [],
        "xs": [
           "xsac_ui5_sb",
           "xsac_ui5_fesv6",
           "xsac_portal_serv",
           "xsac_services",
           "xsac_mess_srv",
           "xsac_alm_pi_ui",
           "xsac_xsa_cockpit"
        ]
      },
      "xsa": {
        "routing": "ports"
      },
      "shine": {
        "email": "shinedemo@microsoft.com"
      },
      "loadbalancer": {}
    }
  ],
  "application": {
    "sid": "HN1",
    "enable_deployment": false,
    "scs_instance_number": "01",
    "ers_instance_number": "02",
    "scs_high_availability": false,
    "application_server_count": 1,
    "webdispatcher_count": 1,
    "vm_sizing": "Default",
    "authentication": {
      "type": "key",
      "username": "azureadm"
    },
    "os": {
      "publisher": "suse",
      "offer": "sles-sap-12-sp5",
      "sku": "gen1"
    }
  },
  "software": {
    "storage_account_sapbits": {
      "is_existing": true,
      "account_tier": "Standard",
      "account_replication_type": "LRS",
      "account_kind": "FileStorage",
      "file_share_name": "bits",
      "container_access_type": "private",
      "arm_id": "VAR_STORAGE_ACCOUNT_ID"
    },
    "downloader": {
      "credentials": {
        "sap_user": "",
        "sap_password": ""
      },
      "scenarios": [
        {
          "scenario_type": "DB",
          "product_name": "HANA",
          "product_version": "2.0",
          "os_type": "LINUX_X64",
          "os_version": "SLES12.3",
          "components": [
            "PLATFORM"
          ]
        },
        {
          "scenario_type": "RTI",
          "product_name": "RTI",
          "os_type": "LINUX_X64"
        },
        {
          "scenario_type": "BASTION",
          "os_type": "NT_X64"
        }
      ],
      "debug": {
        "enabled": false,
        "cert": "charles.pem",
        "proxies": {
          "http": "http://127.0.0.1:8888",
          "https": "https://127.0.0.1:8888"
        }
      }
    }
  },
  "sshkey": {
    "path_to_public_key": "~/.ssh/id_rsa.pub",
    "path_to_private_key": "~/.ssh/id_rsa"
  },
  "options": {
    "enable_secure_transfer": true,
    "ansible_execution": false,
    "enable_prometheus": false
  }
}

thnx
Marcin

**Comment by polichtm** [comment]
This appears to be winrm misconfiguration (or rather lack of it) within the OS of the jumpbox VM. 
To resolve it, it is sufficient to run winrm qc - as per the screenshot below:

![image](https://user-images.githubusercontent.com/10284906/95114163-83ae2a80-0711-11eb-8a5f-2b70f8d5e1c6.png)
 
I assume this should be automatically configured - correct?
rgds
Marcin

**Comment by rukawata** [comment]
Hi Marcin @polichtm,
The automation suppose to run a ps script  ([check here](https://github.com/Azure/sap-hana/blob/master/deploy/terraform/modules/jumpbox/winrm_files/winrm.ps1)) that will configure winrm.

We will look into why this stopped working.

Thanks,
Nancy

**Comment by polichtm** [comment]
Hi @rukawata Nancy,
appreciated

thnx
Marcin

**Comment by rukawata** [comment]
Hi Marcin @polichtm ,
Sorry for the delay. Unfortunately I can't reproduce the same issue you encoutered.
I provisioned a windows jumpbox with the same information you provided:
![image](https://user-images.githubusercontent.com/38501271/96518896-b9c6d080-1220-11eb-8d2b-1dbaada7ba98.png)
And from rti, ansible was able to logon the windows VM:
```
PLAY [jumpboxes_windows] *********************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************
ok: [10.0.1.4]

TASK [windows-jumpboxes-install : Collect components for Windows jumpboxes] ******************************************************
ok: [10.0.1.4] => (item={'authentication': {'password': 'Sap@hana2019!', 'type': 'password', 'username': 'azureadm'}, 'components': [], 'destroy_after_deploy': 'false', 'disk_type': 'StandardSSD_LRS', 'name': 'hanav2jmp-vm0', 'os': {'offer': 'WindowsServer', 'publisher': 'MicrosoftWindowsServer', 'sku': '2019-Datacenter'}, 'private_ip_address': '10.0.1.4', 'public_ip_address': '51.140.182.227', 'size': 'Standard_D2s_v3'})

TASK [windows-jumpboxes-install : Flatten components to have one list for all Windows jumpboxes] *********************************
ok: [10.0.1.4]

TASK [Install components for Windows jumpboxes] **********************************************************************************

PLAY RECAP ***********************************************************************************************************************
10.0.1.4                   : ok=3    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
localhost                  : ok=13   changed=6    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
```

**Comment by polichtm** [comment]
Hi @rukawata  Nancy,
appreciate the follow up. 
I gather it's one of those odd timing issues that I seem to have the tendency to run into once in a while. It's the last step in the deployment which can be easily resolved manually - I'll be closing this bug if nobody else is complaining ;)
rgds
Marcin
